AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation managed taskdefinition

Resources:
  taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: 'arn:aws:iam::<ACCOUNT_ID_PLACEHOLDER>:role/Viite-TaskExecutionRole'
      ContainerDefinitions:
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: /Viite/Prod-Viite-ECS-logs
            awslogs-region: eu-west-1
            awslogs-stream-prefix: Viite
        PortMappings:
          - HostPort: 9080
            Protocol: tcp
            ContainerPort: 9080
        Cpu: 0
        Environment:
          - Name: userProvider
            Value: fi.liikennevirasto.digiroad2.dao.PostGISUserProvider
          - Name: municipalityProvider
            Value: fi.liikennevirasto.digiroad2.dao.PostGISMunicipalityProvider
          - Name: eventBus
            Value: fi.liikennevirasto.digiroad2.DigiroadEventBus
          - Name: vvhServiceHost
            Value: haproxy.vayla.fi
          - Name: oagProxyServer
            Value: oag.vayla.fi
          - Name: oagProxyURL
            Value: 'https://oag.vayla.fi'
          - Name: rasterServiceURL
            Value: 'https://oag.vayla.fi/rasteripalvelu-mml'
          - Name: vvhRestApiEndPoint
            Value: 'https://haproxy.vayla.fi:2027/vvhdata/'
          - Name: vvhRoadlink.frozen
            Value: 'true'
          - Name: vkmUrl
            Value: 'https://api.vaylapilvi.fi'
          - Name: http.proxySet
            Value: 'false'
          - Name: http.proxyHost
            Value: 127.0.0.1
          - Name: http.nonProxyHosts
            Value: 127.0.0.1
          - Name: importOnlyCurrent
            Value: 'false'
          - Name: authenticationTestMode
            Value: 'false'
          - Name: bonecp.jdbcUrl
            Value: 'jdbc:postgresql://rdspg13prod.chw6qe2cqnfv.eu-west-1.rds.amazonaws.com:5432/viite'
          - Name: bonecp.username
            Value: viite
          - Name: conversion.bonecp.jdbcUrl
            Value: 'jdbc:postgresql://vd1bbyq5el8tjd2.c8dj2qlvf50d.eu-west-1.rds.amazonaws.com:5432/drkonv'
          - Name: conversion.bonecp.username
            Value: drkonv
          - Name: authentication.admin.basic.username
            Value: admin
          - Name: env
            Value: Prod
        Secrets:
          - Name: bonecp.password
            Value: 'arn:aws:ssm:eu-west-1:<ACCOUNT_ID_PLACEHOLDER>:parameter/Viite/Prod/rds.viite.db.password'
          - Name: conversion.bonecp.password
            Value: 'arn:aws:ssm:eu-west-1:<ACCOUNT_ID_PLACEHOLDER>:parameter/Viite/Prod/conversion.db.password'
          - Name: authentication.admin.basic.password
            Value: 'arn:aws:ssm:eu-west-1:<ACCOUNT_ID_PLACEHOLDER>:parameter/Viite/Prod/authentication.admin.basic.password'
          - Name: vkmApiKey
            Value: 'arn:aws:ssm:eu-west-1:<ACCOUNT_ID_PLACEHOLDER>:parameter/Viite/Prod/vkmApiKey'
        MemoryReservation: 2048
        Image: '783354560127.dkr.ecr.eu-west-1.amazonaws.com/viite-prod:latest'
        Name: Viite-prod
        HealthCheck:
          StartPeriod: 15
          Command:
            - CMD-SHELL
            - 'curl -f http://127.0.0.1:9080/api/ping/ || exit 1'
      Memory: '4096'
      # TaskRoleArn: ''
      Family: Prod-Viite
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '2048'
      Tags:
        - Key: Name
          Value: Viite-prod
        - Key: Environment
          Value: Prod
        - Key: Owner
          Value: Vaylavirasto
        - Key: Project
          Value: Viite
        - Key: Application
          Value: Viite
