-- Create new columns for ELY/EVK information, a generic ROAD_MAINTAINER

ALTER TABLE ROADWAY ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT 'EVK0';
ALTER TABLE PROJECT_LINK ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT 'EVK0';
ALTER TABLE PROJECT ADD COLUMN IF NOT EXISTS ROAD_MAINTAINERS VARCHAR(5)[] DEFAULT ARRAY['EVK0'] NOT NULL; --int4[]
ALTER TABLE PROJECT_LINK_HISTORY ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT 'EVK0';
ALTER TABLE MUNICIPALITY ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT 'EVK0';
ALTER TABLE ROADWAY_CHANGES ADD COLUMN IF NOT EXISTS NEW_ROAD_MAINTAINER VARCHAR(5) DEFAULT 'EVK0';
ALTER TABLE ROADWAY_CHANGES ADD COLUMN IF NOT EXISTS OLD_ROAD_MAINTAINER VARCHAR(5) DEFAULT 'EVK0';
