--ALTER TABLE PROJECT
--DROP COLUMN TR_ID;


-- Change linkId type from BigInt to VarChar for KGV ids - VIITE-2783.
--ALTER TABLE CALIBRATION_POINT DROP constraint cp_link_fk;
--ALTER TABLE LINEAR_LOCATION DROP constraint LINEAR_LOCATION_LINK_FK;

--ALTER TABLE CALIBRATION_POINT ALTER COLUMN LINK_ID TYPE VARCHAR;
--ALTER TABLE LINK ALTER COLUMN ID TYPE VARCHAR;
--ALTER TABLE LINEAR_LOCATION ALTER COLUMN LINK_ID TYPE VARCHAR;
--ALTER TABLE PROJECT_LINK_HISTORY ALTER COLUMN LINK_ID TYPE VARCHAR, ALTER COLUMN CONNECTED_LINK_ID TYPE VARCHAR;
--ALTER TABLE PROJECT_LINK ALTER COLUMN LINK_ID TYPE VARCHAR, ALTER COLUMN CONNECTED_LINK_ID TYPE VARCHAR;
--ALTER TABLE COMPLEMENTARY_FILTER ALTER COLUMN LINK_ID TYPE VARCHAR;
--ALTER TABLE UNADDRESSED_ROAD_LINK ALTER COLUMN LINK_ID TYPE VARCHAR;

--ALTER TABLE CALIBRATION_POINT add CONSTRAINT CP_LINK_FK FOREIGN KEY (LINK_ID) REFERENCES LINK (ID);
--ALTER TABLE LINEAR_LOCATION add CONSTRAINT LINEAR_LOCATION_LINK_FK FOREIGN KEY (LINK_ID) REFERENCES LINK (ID);

-- Create new columns for ELY/EVK information, a generic ROAD_MAINTAINER

ALTER TABLE ROADWAY ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT null;
ALTER TABLE PROJECT_LINK ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT null;
ALTER TABLE PROJECT ADD COLUMN IF NOT EXISTS ROAD_MAINTAINERS VARCHAR(5)[] DEFAULT '{}' NOT NULL; --int4[]
ALTER TABLE PROJECT_LINK_HISTORY ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT null;
ALTER TABLE MUNICIPALITY ADD COLUMN IF NOT EXISTS ROAD_MAINTAINER VARCHAR(5) DEFAULT null;
ALTER TABLE ROADWAY_CHANGES ADD COLUMN IF NOT EXISTS NEW_ROAD_MAINTAINER VARCHAR(5) DEFAULT null;
ALTER TABLE ROADWAY_CHANGES ADD COLUMN IF NOT EXISTS OLD_ROAD_MAINTAINER VARCHAR(5) DEFAULT null;
