-- Drop old obsolete columns for ely information

ALTER TABLE ROADWAY DROP COLUMN IF EXISTS ELY;
ALTER TABLE PROJECT_LINK DROP COLUMN IF EXISTS ELY;
ALTER TABLE PROJECT DROP COLUMN IF EXISTS ELYS;
ALTER TABLE PROJECT_LINK_HISTORY DROP COLUMN IF EXISTS ELY;
ALTER TABLE ROADWAY_CHANGES DROP COLUMN IF EXISTS NEW_ELY,
DROP COLUMN IF EXISTS OLD_ELY;
