CREATE TABLE NOTIFICATION_BANNER (
  ID SMALLINT NOT NULL DEFAULT 1,
  MESSAGE TEXT NOT NULL DEFAULT '',
  CONSTRAINT NOTIFICATION_BANNER_CHK CHECK (id = 1),
  CONSTRAINT NOTIFICATION_BANNER_PK PRIMARY KEY (ID)
);