--------------------------------------------------------
--  DDL for the road address initial import data table
--  VVH_TIEOSOITE_KESAKUU_2020
--------------------------------------------------------

CREATE TABLE VVH_TIEOSOITE_KESAKUU_2020 (
	ID BIGINT,
	TIEOSOITEID BIGINT,
	LINKID BIGINT,
	ALKU INTEGER,
	LOPPU INTEGER,
	TIE INTEGER,
	LAKKAUTUSPVM DATE,
	AJR SMALLINT,
	AOSA INTEGER,
	AET INTEGER,
	LET INTEGER,
	ELY SMALLINT,
	TIETYYPPI SMALLINT,
	JATKUU SMALLINT,
	AJORATAID BIGINT,
	ALKUPVM DATE,
	LOPPUPVM DATE,
	ALKUX NUMERIC(38,8),
	ALKUY NUMERIC(38,8),
	LOPPUX NUMERIC(38,8),
	LOPPUY NUMERIC(38,8),
	MUUTOSPVM TIMESTAMP,
	KAYTTAJA VARCHAR(10),
	REKISTEROINTIPVM TIMESTAMP,
	HAARA VARCHAR(17),
	KAANNETTY SMALLINT DEFAULT 0,
	ALKU_KALIBROINTIPISTE SMALLINT DEFAULT 0,
	LOPPU_KALIBROINTIPISTE SMALLINT DEFAULT 0,
	KALIBROINTIKOODI SMALLINT DEFAULT 0,
	KALIBROINTI_AET INTEGER,
	KALIBROINTI_LET INTEGER
);
