--------------------------------------------------------
--  DDL for Tables AJORATA, AJORADAN_PISTE,
--  SOLMU, SOLMUKOHTA, LIITTYMA, LIITTYMAKOHTA
--  and View AJORADAN_PISTE_VIEW,
--  used in CONVERSION Database for Initial Import
--  of Nodes and Junctions from Road Register.
--  Run the scripts to Conversion database,
--  use Database Copy for data import.
--------------------------------------------------------

  CREATE TABLE AJORATA
   (	ID BIGINT,
	TILA VARCHAR(1 BYTE) NOT NULL,
	AJORATA SMALLINT NOT NULL,
	TIE INTEGER NOT NULL,
	OSA INTEGER NOT NULL,
	AET INTEGER NOT NULL,
	LET INTEGER NOT NULL,
	JATKUU SMALLINT NOT NULL,
	LAKKAUTUSPVM DATE,
	PIIRINRO SMALLINT NOT NULL,
	ID_TIETYYPPI BIGINT NOT NULL,
	ID_PROJEKTI BIGINT,
	ALKUPVM DATE NOT NULL,
	MUUTOSPVM TIMESTAMP NOT NULL,
	KAYTTAJA VARCHAR(10 BYTE) NOT NULL,
	REKISTEROINTIPVM TIMESTAMP NOT NULL,
	 CONSTRAINT PK_AJORATA PRIMARY KEY (ID)
   );

  CREATE INDEX AJORATA_IND1 ON AJORATA (TIE, OSA, AET);
  CREATE INDEX AJORATA_IND2 ON AJORATA (TIE, OSA);
  CREATE INDEX AJORATA_IND3 ON AJORATA (TIE, OSA, AJORATA);
  CREATE INDEX AJORATA_IND4 ON AJORATA (TIE, OSA, AJORATA, AET);
  CREATE INDEX AJORATA_IND5 ON AJORATA (LAKKAUTUSPVM, TRUNC(ALKUPVM));
  CREATE INDEX AJORATA_IND6 ON AJORATA (ALKUPVM, LAKKAUTUSPVM, ID, TIE, OSA, AJORATA, PIIRINRO);

  CREATE TABLE AJORADAN_PISTE
   (	ID BIGINT,
	ID_AJORATA BIGINT NOT NULL,
	ETAISYYS INTEGER NOT NULL,
	MUUTOSPVM TIMESTAMP NOT NULL,
	KAYTTAJA VARCHAR(10 BYTE) NOT NULL,
	REKISTEROINTIPVM TIMESTAMP NOT NULL,
	 CONSTRAINT PK_AJORADAN_PISTE PRIMARY KEY (ID)
   ) ;

  CREATE INDEX AJORADAN_PISTE_IND1 ON AJORADAN_PISTE (ID_AJORATA, ETAISYYS) ;
  CREATE INDEX AJORADAN_PISTE_IND2 ON AJORADAN_PISTE (ID_AJORATA);
  CREATE INDEX AJORADAN_PISTE_IND3 ON AJORADAN_PISTE (ID_AJORATA, ID, ETAISYYS);

  CREATE TABLE SOLMU
   (	ID BIGINT,
	SOLMUNRO BIGINT NOT NULL,
	X BIGINT NOT NULL,
	Y BIGINT NOT NULL,
	NIMI VARCHAR(40 BYTE),
	SELITE VARCHAR(256 BYTE),
	SOLMUN_TYYPPI BIGINT NOT NULL,
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	MUUTOSPVM TIMESTAMP NOT NULL,
	KAYTTAJA VARCHAR(10 BYTE) NOT NULL,
	REKISTEROINTIPVM TIMESTAMP NOT NULL,
	 CONSTRAINT PK_SOLMU PRIMARY KEY (ID)
  );

  CREATE INDEX SOLMU_IND1 ON SOLMU (SOLMUNRO);

  CREATE TABLE SOLMUKOHTA
   (	ID BIGINT,
	EJ VARCHAR(1 BYTE) NOT NULL,
	ID_TIEOSOITE BIGINT NOT NULL,
	ID_SOLMU BIGINT NOT NULL,
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	MUUTOSPVM TIMESTAMP NOT NULL,
	KAYTTAJA VARCHAR(10 BYTE) NOT NULL,
	REKISTEROINTIPVM TIMESTAMP NOT NULL,
	 CONSTRAINT PK_SOLMUKOHTA PRIMARY KEY (ID)
   );

  CREATE INDEX SOLMUKOHTA_IND1 ON SOLMUKOHTA (ID_TIEOSOITE);
  CREATE INDEX SOLMUKOHTA_IND2 ON SOLMUKOHTA (ID_SOLMU);

 CREATE TABLE LIITTYMA
   (	ID BIGINT,
	LIITTYMANRO SMALLINT NOT NULL,
	ERITASO VARCHAR(3 BYTE),
	VALO_OHJAUS SMALLINT,
	ID_SOLMU BIGINT NOT NULL,
	ID_LIITTYMALUOKKA BIGINT,
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	VALOALKUPVM DATE,
	MUUTOSPVM TIMESTAMP NOT NULL,
	KAYTTAJA VARCHAR(10 BYTE) NOT NULL,
	REKISTEROINTIPVM TIMESTAMP NOT NULL,
	 CONSTRAINT PK_LIITTYMA PRIMARY KEY (ID)
   );

  CREATE INDEX LIITTYMA_IND1 ON LIITTYMA (ID_SOLMU);

  CREATE TABLE LIITTYMAKOHTA
   (	ID BIGINT,
	EJ VARCHAR(1 BYTE) NOT NULL,
	ID_AJORADAN_PISTE BIGINT NOT NULL,
	ID_LIITTYMA BIGINT,
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	MUUTOSPVM TIMESTAMP NOT NULL,
	KAYTTAJA VARCHAR(10 BYTE) NOT NULL,
	REKISTEROINTIPVM TIMESTAMP NOT NULL,
	 CONSTRAINT PK_LIITTYMAKOHTA PRIMARY KEY (ID)
   );

  CREATE INDEX LIITTYMAKOHTA_IND1 ON LIITTYMAKOHTA (ID_AJORADAN_PISTE);
  CREATE INDEX LIITTYMAKOHTA_IND2 ON LIITTYMAKOHTA (ID_LIITTYMA);
  CREATE INDEX LIITTYMAKOHTA_IND3 ON LIITTYMAKOHTA (ID_AJORADAN_PISTE, EJ) ;

  CREATE OR REPLACE FORCE VIEW AJORADAN_PISTE_VIEW (ID, ID_AJORATA, TIE, OSA, AJORATA, ETAISYYS, MUUTOSPVM, KAYTTAJA, REKISTEROINTIPVM ) AS
  SELECT A.ID, A.ID_AJORATA, B.TIE, B.OSA, B.AJORATA, A.ETAISYYS, A.MUUTOSPVM, A.KAYTTAJA, A.REKISTEROINTIPVM
  FROM AJORADAN_PISTE A, AJORATA B
  WHERE A.ID_AJORATA=B.ID ;