  CREATE TABLE AJORATA
   (	ID NUMBER(*,0),
	TILA VARCHAR2(1 BYTE) NOT NULL,
	AJORATA NUMBER(1,0) NOT NULL,
	TIE NUMBER(5,0) NOT NULL,
	OSA NUMBER(5,0) NOT NULL,
	AET NUMBER(5,0) NOT NULL,
	LET NUMBER(5,0) NOT NULL,
	JATKUU NUMBER(1,0) NOT NULL,
	LAKKAUTUSPVM DATE,
	PIIRINRO NUMBER(2,0) NOT NULL,
	ID_TIETYYPPI NUMBER(*,0) NOT NULL,
	ID_PROJEKTI NUMBER(*,0),
	ALKUPVM DATE NOT NULL,
	MUUTOSPVM DATE NOT NULL,
	KAYTTAJA VARCHAR2(10 BYTE) NOT NULL,
	REKISTEROINTIPVM DATE NOT NULL,
	 CONSTRAINT PK_AJORATA PRIMARY KEY (ID)
   );

  CREATE INDEX AJORATA_IND1 ON AJORATA (TIE, OSA, AET);
  CREATE INDEX AJORATA_IND2 ON AJORATA (TIE, OSA);
  CREATE INDEX AJORATA_IND3 ON AJORATA (TIE, OSA, AJORATA);
  CREATE INDEX AJORATA_IND4 ON AJORATA (TIE, OSA, AJORATA, AET);
  CREATE INDEX AJORATA_IND5 ON AJORATA (LAKKAUTUSPVM, TRUNC(ALKUPVM));
  CREATE INDEX AJORATA_IND6 ON AJORATA (ALKUPVM, LAKKAUTUSPVM, ID, TIE, OSA, AJORATA, PIIRINRO);

  CREATE TABLE AJORADAN_PISTE
   (	ID NUMBER(*,0),
	ID_AJORATA NUMBER(*,0) NOT NULL,
	ETAISYYS NUMBER(5,0) NOT NULL,
	MUUTOSPVM DATE NOT NULL,
	KAYTTAJA VARCHAR2(10 BYTE) NOT NULL,
	REKISTEROINTIPVM DATE NOT NULL,
	 CONSTRAINT PK_AJORADAN_PISTE PRIMARY KEY (ID)
   ) ;

  CREATE INDEX AJORADAN_PISTE_IND1 ON AJORADAN_PISTE (ID_AJORATA, ETAISYYS) ;
  CREATE INDEX AJORADAN_PISTE_IND2 ON AJORADAN_PISTE (ID_AJORATA);
  CREATE INDEX AJORADAN_PISTE_IND3 ON AJORADAN_PISTE (ID_AJORATA, ID, ETAISYYS);

  CREATE TABLE SOLMU
   (	ID NUMBER(*,0),
	SOLMUNRO NUMBER(9,0) NOT NULL,
	X NUMBER(7,0) NOT NULL,
	Y NUMBER(7,0) NOT NULL,
	NIMI VARCHAR2(40 BYTE),
	SELITE VARCHAR2(256 BYTE),
	ID_SOLMUN_TYYPPI NUMBER(*,0) NOT NULL,
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	MUUTOSPVM DATE NOT NULL,
	KAYTTAJA VARCHAR2(10 BYTE) NOT NULL,
	REKISTEROINTIPVM DATE NOT NULL,
	 CONSTRAINT PK_SOLMU PRIMARY KEY (ID)
  );

  CREATE INDEX SOLMU_IND1 ON SOLMU (SOLMUNRO);

  CREATE TABLE SOLMUKOHTA
   (	ID NUMBER(*,0),
	EJ VARCHAR2(1 BYTE) NOT NULL,
	ID_TIEOSOITE NUMBER(*,0) NOT NULL,
	ID_SOLMU NUMBER(*,0) NOT NULL,
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	MUUTOSPVM DATE NOT NULL,
	KAYTTAJA VARCHAR2(10 BYTE) NOT NULL,
	REKISTEROINTIPVM DATE NOT NULL,
	 CONSTRAINT PK_SOLMUKOHTA PRIMARY KEY (ID)
   );

  CREATE INDEX SOLMUKOHTA_IND1 ON SOLMUKOHTA (ID_TIEOSOITE);
  CREATE INDEX SOLMUKOHTA_IND2 ON SOLMUKOHTA (ID_SOLMU);

 CREATE TABLE LIITTYMA
   (	ID NUMBER(*,0),
	LIITTYMANRO NUMBER(2,0) NOT NULL,
	ERITASO VARCHAR2(3 BYTE),
	VALO_OHJAUS NUMBER(2,0),
	ID_SOLMU NUMBER(*,0) NOT NULL,
	ID_LIITTYMALUOKKA NUMBER(*,0),
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	VALOALKUPVM DATE,
	MUUTOSPVM DATE NOT NULL,
	KAYTTAJA VARCHAR2(10 BYTE) NOT NULL,
	REKISTEROINTIPVM DATE NOT NULL,
	 CONSTRAINT PK_LIITTYMA PRIMARY KEY (ID)
   );

  CREATE INDEX LIITTYMA_IND1 ON LIITTYMA (ID_SOLMU);

  CREATE TABLE LIITTYMAKOHTA
   (	ID NUMBER(*,0),
	EJ VARCHAR2(1 BYTE) NOT NULL,
	ID_AJORADAN_PISTE NUMBER(*,0) NOT NULL,
	ID_LIITTYMA NUMBER(*,0),
	VOIMASSAOLOAIKA_ALKU DATE NOT NULL,
	VOIMASSAOLOAIKA_LOPPU DATE,
	MUUTOSPVM DATE NOT NULL,
	KAYTTAJA VARCHAR2(10 BYTE) NOT NULL,
	REKISTEROINTIPVM DATE NOT NULL,
	 CONSTRAINT PK_LIITTYMAKOHTA PRIMARY KEY (ID)
   );

  CREATE INDEX LIITTYMAKOHTA_IND1 ON LIITTYMAKOHTA (ID_AJORADAN_PISTE);
  CREATE INDEX LIITTYMAKOHTA_IND2 ON LIITTYMAKOHTA (ID_LIITTYMA);
  CREATE INDEX LIITTYMAKOHTA_IND3 ON LIITTYMAKOHTA (ID_AJORADAN_PISTE, EJ) ;

  CREATE OR REPLACE FORCE VIEW AJORADAN_PISTE_VIEW (ID, ID_AJORATA, TIE, OSA, AJORATA, ETAISYYS, MUUTOSPVM, KAYTTAJA, REKISTEROINTIPVM ) AS
  SELECT A.ID, A.ID_AJORATA, B.TIE, B.OSA, B.AJORATA, A.ETAISYYS, A.MUUTOSPVM, A.KAYTTAJA, A.REKISTEROINTIPVM
  FROM AJORADAN_PISTE A, AJORATA B
  WHERE A.ID_AJORATA=B.ID ;