

  CREATE TABLE "COMPLEMENTARY_FILTER"
   (	"LINK_ID" NUMBER(38,0) NOT NULL ENABLE,
	 CONSTRAINT "COMPLEMENTARY_FILTER_PK" PRIMARY KEY ("LINK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "EXPORT_LOCK"
   (	"ID" NUMBER(1,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(4000),
	 CONSTRAINT "EXPORT_LOCK_CHK" CHECK (id = 1) ENABLE,
	 CONSTRAINT "EXPORT_LOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE TABLE "JUNCTION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"JUNCTION_NUMBER" NUMBER(2,0),
	"START_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	"VALID_TO" DATE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"NODE_NUMBER" NUMBER,
	 CONSTRAINT "JUNCTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "LINK"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SOURCE" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"ADJUSTED_TIMESTAMP" NUMBER(13,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT "LINK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "MUNICIPALITY"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"NAME_FI" VARCHAR2(128),
	"NAME_SV" VARCHAR2(128),
	"ELY_NRO" NUMBER(2,0),
	"ROAD_MAINTAINER_ID" NUMBER(38,0),
	 CONSTRAINT "MUNICIPALITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "MUNI_ELY_MANTAINER_UK" UNIQUE ("ID", "ELY_NRO", "ROAD_MAINTAINER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "NODE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NODE_NUMBER" NUMBER(9,0) NOT NULL ENABLE,
	"COORDINATES" "SDO_GEOMETRY" NOT NULL ENABLE,
	"NAME" VARCHAR2(30 CHAR),
	"TYPE" NUMBER NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	"VALID_TO" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"PUBLISHED_TIME" DATE,
	"EDITOR" VARCHAR2(32),
	"REGISTRATION_DATE" DATE DEFAULT TO_DATE('1900', 'yyyy') NOT NULL ENABLE,
	 CONSTRAINT "NODE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PROJECT"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"STATE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"NAME" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(32),
	"MODIFIED_DATE" DATE,
	"ADD_INFO" VARCHAR2(1000),
	"START_DATE" DATE,
	"STATUS_INFO" VARCHAR2(1000),
	"TR_ID" NUMBER(38,0),
	"COORD_X" NUMBER(10,3),
	"COORD_Y" NUMBER(10,3),
	"ZOOM" NUMBER(2,0),
	 CONSTRAINT "PROJECT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PUBLISHED_ROAD_NETWORK"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) NOT NULL ENABLE,
	"VALID_TO" TIMESTAMP (6),
	 CONSTRAINT "PUBLISHED_ROAD_NETWORK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "ROADWAY"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"ROADWAY_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER(5,0) NOT NULL ENABLE,
	"ROAD_PART_NUMBER" NUMBER(5,0) NOT NULL ENABLE,
	"TRACK" NUMBER(2,0) NOT NULL ENABLE,
	"START_ADDR_M" NUMBER(8,0) NOT NULL ENABLE,
	"END_ADDR_M" NUMBER(8,0) NOT NULL ENABLE,
	"REVERSED" NUMBER(1,0) NOT NULL ENABLE,
	"DISCONTINUITY" NUMBER(1,0) NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	"ROAD_TYPE" NUMBER(2,0) NOT NULL ENABLE,
	"ELY" NUMBER(2,0),
	"TERMINATED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"VALID_TO" DATE,
	 CONSTRAINT "TERMINATION_END_DATE_CHK" CHECK (TERMINATED = 0 OR (TERMINATED in (1,2) AND END_DATE IS NOT NULL)) ENABLE,
	 CONSTRAINT "ROADWAY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "ROADWAY_HISTORY_UK" UNIQUE ("ROAD_NUMBER", "ROAD_PART_NUMBER", "START_ADDR_M", "END_ADDR_M", "TRACK", "DISCONTINUITY", "START_DATE", "END_DATE", "VALID_FROM", "VALID_TO", "ELY", "ROAD_TYPE", "TERMINATED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "ROADWAY_CHANGES"
   (	"PROJECT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"CHANGE_TYPE" NUMBER(2,0) NOT NULL ENABLE,
	"OLD_ROAD_NUMBER" NUMBER(5,0),
	"NEW_ROAD_NUMBER" NUMBER(5,0),
	"OLD_ROAD_PART_NUMBER" NUMBER(5,0),
	"NEW_ROAD_PART_NUMBER" NUMBER(5,0),
	"OLD_TRACK" NUMBER(2,0),
	"NEW_TRACK" NUMBER(2,0),
	"OLD_START_ADDR_M" NUMBER(8,0),
	"NEW_START_ADDR_M" NUMBER(8,0),
	"OLD_END_ADDR_M" NUMBER(8,0),
	"NEW_END_ADDR_M" NUMBER(8,0),
	"NEW_DISCONTINUITY" NUMBER(1,0) NOT NULL ENABLE,
	"NEW_ROAD_TYPE" NUMBER(2,0) NOT NULL ENABLE,
	"NEW_ELY" NUMBER(2,0) NOT NULL ENABLE,
	"OLD_ROAD_TYPE" NUMBER(2,0),
	"OLD_DISCONTINUITY" NUMBER(1,0),
	"OLD_ELY" NUMBER(2,0),
	"REVERSED" NUMBER(1,0) DEFAULT 0,
	"ROADWAY_CHANGE_ID" NUMBER(8,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "ROADWAY_POINT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROADWAY_NUMBER" NUMBER NOT NULL ENABLE,
	"ADDR_M" NUMBER NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"MODIFIED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT "ROADWAY_POINT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "ROADWAY_POINT_UK1" UNIQUE ("ROADWAY_NUMBER", "ADDR_M") DEFERRABLE INITIALLY DEFERRED
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "ROAD_NAME"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER(5,0) NOT NULL ENABLE,
	"ROAD_NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"VALID_TO" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	 CONSTRAINT "ROAD_NAME_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "SERVICE_USER"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"USERNAME" VARCHAR2(256) NOT NULL ENABLE,
	"CONFIGURATION" VARCHAR2(4000),
	 CONSTRAINT "SERVICE_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "SERVICE_USER_UK" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE GLOBAL TEMPORARY TABLE "TEMP_ID"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	 CONSTRAINT "TEMP_ID_PK" PRIMARY KEY ("ID") ENABLE
   ) ON COMMIT DELETE ROWS ;

  CREATE TABLE "UNADDRESSED_ROAD_LINK"
   (	"LINK_ID" NUMBER(38,0) NOT NULL ENABLE,
	"START_ADDR_M" NUMBER(8,0),
	"END_ADDR_M" NUMBER(8,0),
	"ROAD_NUMBER" NUMBER(5,0),
	"ROAD_PART_NUMBER" NUMBER(5,0),
	"ANOMALY_CODE" NUMBER(2,0) NOT NULL ENABLE,
	"START_M" NUMBER(8,3),
	"END_M" NUMBER(8,3),
	"GEOMETRY" "SDO_GEOMETRY"
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "CALIBRATION_POINT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROADWAY_POINT_ID" NUMBER NOT NULL ENABLE,
	"LINK_ID" NUMBER NOT NULL ENABLE,
	"START_END" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"TYPE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"VALID_TO" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT "CP_START_END_CHK" CHECK (START_END in (0,1)) ENABLE,
	 CONSTRAINT "CALIBRATION_POINT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "CP_TYPE_CHK" CHECK ("TYPE" in (1, 2, 3)) ENABLE,
	 CONSTRAINT "CP_ROADWAY_POINT_FK" FOREIGN KEY ("ROADWAY_POINT_ID")
	  REFERENCES "ROADWAY_POINT" ("ID") ENABLE,
	 CONSTRAINT "CP_LINK_FK" FOREIGN KEY ("LINK_ID")
	  REFERENCES "LINK" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "JUNCTION_POINT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"BEFORE_AFTER" NUMBER(1,0) NOT NULL ENABLE,
	"ROADWAY_POINT_ID" NUMBER NOT NULL ENABLE,
	"JUNCTION_ID" NUMBER NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"VALID_TO" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT "JUNCTION_POINT_CHK1" CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))) ENABLE,
	 CONSTRAINT "JUNCTION_POINT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "JUNCTION_POINT_FK1" FOREIGN KEY ("JUNCTION_ID")
	  REFERENCES "JUNCTION" ("ID") ENABLE,
	 CONSTRAINT "FK_JP_ROADWAY_POINT_ID" FOREIGN KEY ("ROADWAY_POINT_ID")
	  REFERENCES "ROADWAY_POINT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "LINEAR_LOCATION"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"ROADWAY_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
	"ORDER_NUMBER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"LINK_ID" NUMBER(38,0),
	"START_MEASURE" NUMBER(8,3),
	"END_MEASURE" NUMBER(8,3),
	"SIDE" NUMBER(1,0),
	"GEOMETRY" "SDO_GEOMETRY",
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"VALID_TO" DATE,
	"CREATED_BY" VARCHAR2(128),
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT "LINEAR_LOCATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "LINEAR_LOCATION_UK" UNIQUE ("ROADWAY_NUMBER", "ORDER_NUMBER", "LINK_ID", "START_MEASURE", "END_MEASURE", "VALID_TO", "SIDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "LINEAR_LOCATION_LINK_FK" FOREIGN KEY ("LINK_ID")
	  REFERENCES "LINK" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "NODE_POINT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"BEFORE_AFTER" NUMBER(1,0) NOT NULL ENABLE,
	"ROADWAY_POINT_ID" NUMBER NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"VALID_TO" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	"NODE_NUMBER" NUMBER,
	"TYPE" NUMBER DEFAULT 99 NOT NULL ENABLE,
	 CONSTRAINT "NODE_POINT_CHK1" CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))) ENABLE,
	 CONSTRAINT "NODE_POINT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_NP_ROADWAY_POINT_ID" FOREIGN KEY ("ROADWAY_POINT_ID")
	  REFERENCES "ROADWAY_POINT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PROJECT_LINK_HISTORY"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROJECT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"TRACK" NUMBER(2,0) NOT NULL ENABLE,
	"DISCONTINUITY_TYPE" NUMBER(1,0) DEFAULT 5 NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER(5,0),
	"ROAD_PART_NUMBER" NUMBER(5,0),
	"START_ADDR_M" NUMBER(8,0),
	"END_ADDR_M" NUMBER(8,0),
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(32),
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"MODIFIED_DATE" DATE,
	"STATUS" NUMBER(2,0),
	"ROAD_TYPE" NUMBER(2,0) DEFAULT 99 NOT NULL ENABLE,
	"ROADWAY_ID" NUMBER(38,0),
	"LINEAR_LOCATION_ID" NUMBER(38,0),
	"CONNECTED_LINK_ID" NUMBER(38,0),
	"ELY" NUMBER(2,0),
	"REVERSED" NUMBER(1,0) DEFAULT 0,
	"SIDE" NUMBER(5,0),
	"START_MEASURE" NUMBER(8,3),
	"END_MEASURE" NUMBER(8,3),
	"LINK_ID" NUMBER(38,0),
	"ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
	"LINK_SOURCE" NUMBER(2,0) DEFAULT (1),
	"GEOMETRY" "SDO_GEOMETRY",
	"ORIGINAL_START_ADDR_M" NUMBER(8,0) NOT NULL ENABLE,
	"ORIGINAL_END_ADDR_M" NUMBER(8,0) NOT NULL ENABLE,
	"ROADWAY_NUMBER" NUMBER(38,0),
	"START_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"END_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ORIG_START_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ORIG_END_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "PROJECT_LINK_HIST_PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PROJECT_LINK_NAME"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROJECT_ID" NUMBER(38,0),
	"ROAD_NUMBER" NUMBER(5,0),
	"ROAD_NAME" VARCHAR2(255),
	 CONSTRAINT "PROJECT_LINK_NAME_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "PROJECT_LINK_NAME_UK" UNIQUE ("PROJECT_ID", "ROAD_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "PROJECT_LINK_NAME_PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PROJECT_RESERVED_ROAD_PART"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER(5,0) NOT NULL ENABLE,
	"ROAD_PART_NUMBER" NUMBER(5,0) NOT NULL ENABLE,
	"PROJECT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(128),
	 CONSTRAINT "PROJECT_RESERVED_ROAD_PART_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "RESERVED_ROAD_PROJECT_UK" UNIQUE ("PROJECT_ID", "ROAD_NUMBER", "ROAD_PART_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "PRRP_PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PUBLISHED_ROADWAY"
   (	"NETWORK_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ROADWAY_ID" NUMBER(38,0) NOT NULL ENABLE,
	 CONSTRAINT "PUBLISHED_ROADWAY_PK" PRIMARY KEY ("NETWORK_ID", "ROADWAY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "PUBROADADDR_PUBROADNETWORK_FK" FOREIGN KEY ("NETWORK_ID")
	  REFERENCES "PUBLISHED_ROAD_NETWORK" ("ID") ENABLE,
	 CONSTRAINT "PUBROADADDR_ROADWAY_FK" FOREIGN KEY ("ROADWAY_ID")
	  REFERENCES "ROADWAY" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "ROAD_NETWORK_ERROR"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"ROADWAY_ID" NUMBER(38,0) NOT NULL ENABLE,
	"LINEAR_LOCATION_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ERROR_CODE" NUMBER(38,0) NOT NULL ENABLE,
	"ERROR_TIMESTAMP" NUMBER(38,0) DEFAULT 0,
	"ROAD_NETWORK_VERSION" NUMBER(38,0),
	 CONSTRAINT "ROAD_NETWORK_ERROR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "ADDRESS_ERROR_VERSION_UK" UNIQUE ("ROADWAY_ID", "LINEAR_LOCATION_ID", "ERROR_CODE", "ROAD_NETWORK_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "RNE_ROADWAY_FK" FOREIGN KEY ("ROADWAY_ID")
	  REFERENCES "ROADWAY" ("ID") ENABLE,
	 CONSTRAINT "ROAD_NETWORK_FK" FOREIGN KEY ("ROAD_NETWORK_VERSION")
	  REFERENCES "PUBLISHED_ROAD_NETWORK" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PROJECT_LINK"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROJECT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"TRACK" NUMBER(2,0) NOT NULL ENABLE,
	"DISCONTINUITY_TYPE" NUMBER(1,0) DEFAULT 5 NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER(5,0) CONSTRAINT "ROAD_NOT_NULL" NOT NULL ENABLE,
	"ROAD_PART_NUMBER" NUMBER(5,0) CONSTRAINT "PART_NOT_NULL" NOT NULL ENABLE,
	"START_ADDR_M" NUMBER(8,0),
	"END_ADDR_M" NUMBER(8,0),
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(32),
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"MODIFIED_DATE" DATE,
	"STATUS" NUMBER(2,0),
	"ROAD_TYPE" NUMBER(2,0) DEFAULT 99 NOT NULL ENABLE,
	"ROADWAY_ID" NUMBER(38,0),
	"LINEAR_LOCATION_ID" NUMBER(38,0),
	"CONNECTED_LINK_ID" NUMBER(38,0),
	"ELY" NUMBER(2,0),
	"REVERSED" NUMBER(1,0) DEFAULT 0,
	"SIDE" NUMBER(2,0),
	"START_MEASURE" NUMBER(8,3),
	"END_MEASURE" NUMBER(8,3),
	"LINK_ID" NUMBER(38,0),
	"ADJUSTED_TIMESTAMP" NUMBER(13,0) DEFAULT 0 NOT NULL ENABLE,
	"LINK_SOURCE" NUMBER(2,0) DEFAULT 1,
	"GEOMETRY" "SDO_GEOMETRY",
	"ORIGINAL_START_ADDR_M" NUMBER(8,0) NOT NULL ENABLE,
	"ORIGINAL_END_ADDR_M" NUMBER(8,0) NOT NULL ENABLE,
	"ROADWAY_NUMBER" NUMBER(38,0),
	"START_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"END_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ORIG_START_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ORIG_END_CALIBRATION_POINT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "PROJECT_LINK_ADDRESS_CHK" CHECK ((road_number is null and road_part_number is null) or
    (road_number is not null and road_part_number is not null and start_addr_m is not null and end_addr_m is not null)) ENABLE,
	 CONSTRAINT "PROJECT_LINK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "LINK_RESERVED_FK" FOREIGN KEY ("PROJECT_ID", "ROAD_NUMBER", "ROAD_PART_NUMBER")
	  REFERENCES "PROJECT_RESERVED_ROAD_PART" ("PROJECT_ID", "ROAD_NUMBER", "ROAD_PART_NUMBER") ENABLE,
	 CONSTRAINT "PROJECT_LINK_PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "PROJECT_LINK_ROADWAY_FK" FOREIGN KEY ("ROADWAY_ID")
	  REFERENCES "ROADWAY" ("ID") ENABLE,
	 CONSTRAINT "PROJECT_LINK_LINEAR_LOC_FK" FOREIGN KEY ("LINEAR_LOCATION_ID")
	  REFERENCES "LINEAR_LOCATION" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "ROADWAY_CHANGES_LINK"
   (	"ROADWAY_CHANGE_ID" NUMBER(8,0) NOT NULL ENABLE,
	"PROJECT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROJECT_LINK_ID" NUMBER(38,0) NOT NULL ENABLE,
	 CONSTRAINT "PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ENABLE,
	 CONSTRAINT "PROJECT_LINK_FK" FOREIGN KEY ("PROJECT_LINK_ID")
	  REFERENCES "PROJECT_LINK" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PROJECT_CALIBRATION_POINT"
   (	"ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROJECT_LINK_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROJECT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"LINK_M" NUMBER(8,3) NOT NULL ENABLE,
	"ADDRESS_M" NUMBER(8,0) NOT NULL ENABLE,
	 CONSTRAINT "PROJECT_CALIBRATION_POINT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "PCALPOINT_PLINK_FK" FOREIGN KEY ("PROJECT_LINK_ID")
	  REFERENCES "PROJECT_LINK" ("ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "PCALPOINT_PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
