#!/bin/bash
#
# Start up script for the VIITE server
#
# chkconfig: 345 85 15
# description: VIITE

case "$1" in
  start)
    runuser web -lc $"
      cd /home/web/viite/current
            ./start.sh &"
        ;;
  stop)
    cd /home/web/viite/current
    ./stop.sh || true
        ;;
  *)
          echo $"Usage: $0 {start|stop}"
          exit 2
esac
