#!/bin/bash

# viite          Start up the Viite server daemon

case "$1" in
  start)
    runuser web -lc $"
      cd /home/web/viite/current
	    ./start.sh
	;;
  stop)
    cd /home/web/viite/current
    ./stop.sh
	;;
  *)
	  echo $"Usage: $0 {start|stop}"
	  exit 2
esac
