--TR recovery from backup tables

create table LINEAR_LOCATION_before_5_129 as select * from LINEAR_LOCATION;
create table roadway_before_5_129 as select * from roadway;
create table CALIBRATION_POINT_before_5_129 as select * from CALIBRATION_POINT;
create table ROADWAY_POINT_before_5_129 as select * from ROADWAY_POINT;
create table NODE_POINT_before_5_129 as select * from NODE_POINT;
create table JUNCTION_POINT_before_5_129 as select * from JUNCTION_POINT;
create table ROAD_NAME_before_5_129 as select * from ROAD_NAME;
create table PROJECT_LINK_HISTORY_bf_5_129 as select * from PROJECT_LINK_HISTORY;
create table NODE_before_5_129 as select * from NODE;
create table LINK_before_5_129 as select * from LINK;
create table JUNCTION_before_5_129 as select * from JUNCTION;

create table ROADWAY_CHANGES_vt5_bak as select * from ROADWAY_CHANGES;
create table ROADWAY_CHANGES_LINK_vt5_bak as select * from ROADWAY_CHANGES_LINK;
create table PROJECT_LINK_vt5_bak as select * from PROJECT_LINK;
create table PROJECT_LINK_NAME_vt5_bak as select * from PROJECT_LINK_NAME;
create table PROJECT_RES_ROAD_PART_vt5_bak as select * from PROJECT_RESERVED_ROAD_PART;
create table PROJECT_vt5_bak as select * from PROJECT;

DELETE FROM ROADWAY_CHANGES;
DELETE FROM ROADWAY_CHANGES_LINK;
DELETE FROM PROJECT_LINK;
DELETE FROM PROJECT_LINK_NAME;
DELETE FROM PROJECT_RESERVED_ROAD_PART;
DELETE FROM PROJECT;


DELETE FROM CALIBRATION_POINT;
DELETE FROM NODE_POINT;
DELETE FROM JUNCTION_POINT;
DELETE FROM ROAD_NAME;
DELETE FROM PROJECT_LINK_HISTORY;
DELETE FROM NODE;
--DELETE FROM ROADWAY_CHANGES;
--DELETE FROM ROADWAY_CHANGES_LINK;
DELETE FROM LINEAR_LOCATION;

--DELETE FROM ROADWAY_CHANGES WHERE PROJECT_ID = PRJ_ID;
DELETE FROM LINK;
DELETE FROM JUNCTION;

DELETE FROM ROADWAY_POINT;
DELETE FROM roadway;


INSERT INTO ROADWAY  select * from roadway_before_5_129;
INSERT INTO ROADWAY_POINT  select * from ROADWAY_POINT_before_5_129;
INSERT INTO NODE_POINT  select * from NODE_POINT_before_5_129;
INSERT INTO ROAD_NAME  select * from ROAD_NAME_before_5_129;
INSERT INTO NODE  select * from NODE_before_5_129;
INSERT INTO LINK  select * from LINK_before_5_129;
INSERT INTO CALIBRATION_POINT  select * from CALIBRATION_POINT_before_5_129;
INSERT INTO JUNCTION  select * from JUNCTION_before_5_129;
INSERT INTO JUNCTION_POINT  select * from JUNCTION_POINT_before_5_129;

INSERT INTO LINEAR_LOCATION select * from LINEAR_LOCATION_before_5_129;
-- INSERT INTO LINEAR_LOCATION
-- select ID,ROADWAY_NUMBER,ORDER_NUMBER,LINK_ID,START_MEASURE,END_MEASURE,SIDE,GEOMETRY,VALID_FROM,VALID_TO,CREATED_BY,CREATED_TIME
-- from (select t.*, ROWNUM rnum
--       from (select *
--             from LINEAR_LOCATION_before_5_129
--             order by id) t
--       where ROWNUM <= 500000)
-- where rnum > 400000;

INSERT INTO PROJECT select * FROM PROJECT_bak;
INSERT INTO PROJECT_RESERVED_ROAD_PART select * FROM PROJECT_RESERVED_ROAD_PART_bak;
INSERT INTO PROJECT_LINK_NAME select * FROM PROJECT_LINK_NAME_bak;
INSERT INTO PROJECT_LINK select * FROM PROJECT_LINK_bak;
INSERT INTO ROADWAY_CHANGES_LINK select * FROM ROADWAY_CHANGES_LINK_bak;
INSERT INTO ROADWAY_CHANGES  select * FROM ROADWAY_CHANGES_bak;
INSERT INTO PROJECT_LINK_HISTORY  select * from PROJECT_LINK_HISTORY_bf_5_129;
