AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 bucket for storing SBT launcher and other build tools"

Resources:
  SbtRepoBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "sbt-repository-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SbtRepoBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SbtRepoBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Sub "${SbtRepoBucket.Arn}/*"
            Condition:
              Bool:
                'aws:SecureTransport': false
