FROM node:alpine
ARG JENKINS_UID=10000
RUN adduser -D -S -u $JENKINS_UID jenkins
RUN apk update && apk upgrade && \
    apk add git && \
    apk add yarn && \
    mkdir /home/jenkins/package && \
    mkdir /home/jenkins/package/UI

RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C /
RUN yarn global add phantomjs-prebuilt && \
    yarn global add grunt-cli

RUN chown -R jenkins /home/jenkins
USER jenkins