FROM node:alpine
#RUN apk --update add openjdk8-jre
ARG JENKINS_UID=10000
RUN adduser -D -S -u $JENKINS_UID jenkins
RUN mkdir /home/jenkins/package && \
    mkdir /home/jenkins/package/UI
RUN npm install grunt --global
RUN chown -R jenkins /home/jenkins
USER jenkins