AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation managed taskdefinition for Viite Dev environment with updated parameter names
Parameters:
  RepositoryURL:
    Type: String
    Description: URL to repository, where the container is, e.g. 783354560127.dkr.ecr.eu-west-1.amazonaws.com
  ApiS3ObjectTTLSeconds:
    Type: Number
    Default: 300
    Description: Seconds, how long s3 object can be fetched after last modification
  ECSTaskRoleName:
    Type: String
    Default: Viite-dev-ALB-ECSTaskExecutionRole-1HNI00KIMUQ5O
    Description: Name of ECS task definition task role
  DynamicLinkNetworkS3BucketName:
    Type: String
    Default: dev-vayla-viite-dynamic-link-network-bucket
    Description: Name of s3 bucket for dynamic link network change sets
Resources:
  # This is a role which is used by the ECS tasks themselves.
  ECSTaskExecutionRoleForViite:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:DescribeParameters'
                  # Allow the ECS Tasks to download images from ECR
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'

                  # Allow the ECS tasks to upload logs to CloudWatch
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRoleForViite.Arn
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ECSTaskRoleName}'
      ContainerDefinitions:
        -
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/Viite-ECS-logs
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs
          PortMappings:
            - ContainerPort: 9080
              HostPort: 9080
              Protocol: tcp
          Cpu: 0
          Environment:
            - Name: userProvider
              Value: fi.vaylavirasto.viite.dao.UserProviderDAO
            - Name: eventBus
              Value: fi.liikennevirasto.digiroad2.DigiroadEventBus
            - Name: oagProxyServer
              Value: oag.vayla.fi
            - Name: oagProxyURL
              Value: 'https://oag.vayla.fi'
            - Name: rasterServiceURL
              Value: 'https://api.vaylapilvi.fi/rasteripalvelu-mml'
            - Name: kgvRoadlink.frozen
              Value: 'true'
            - Name: vkmUrl
              Value: 'https://api.vaylapilvi.fi'
            - Name: http.proxySet
              Value: 'false'
            - Name: http.proxyHost
              Value: 127.0.0.1
            - Name: http.nonProxyHosts
              Value: 127.0.0.1
            - Name: importOnlyCurrent
              Value: 'false'
            - Name: authenticationTestMode
              Value: 'false'
            - Name: env
              Value: Dev
            - Name: apiS3ObjectTTLSeconds
              Value: !Ref ApiS3ObjectTTLSeconds
            - Name: dynamicLinkNetworkS3BucketName
              Value: !Ref DynamicLinkNetworkS3BucketName
            - Name: kgvEndpoint
              Value: 'https://api.vaylapilvi.fi/paikkatiedot/ogc/features/v1/collections'
          Secrets:
            - Name: db.jdbcUrl
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/Viite/Dev/db.jdbcUrl'
            - Name: db.username
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/Viite/Dev/db.username'
            - Name: db.password
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/Viite/Dev/db.password'
            - Name: conversion.db.jdbcUrl
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/allEnvs/conversion.db.jdbcUrl'
            - Name: conversion.db.username
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/allEnvs/conversion.db.username'
            - Name: conversion.db.password
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/allEnvs/conversion.db.password'
            - Name: authentication.admin.basic.username
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/allEnvs/authentication.admin.basic.username'
            - Name: authentication.admin.basic.password
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/allEnvs/authentication.admin.basic.password'
            - Name: vkmApiKey
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/vkmApiKey-vkmprod'
            - Name: rasterServiceApiKey
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/allEnvs/rasterServiceApiKey'
            - Name: kgvApiKey
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/kgvApiKey'
            - Name: apiS3BucketName
              ValueFrom: 'arn:aws:ssm:eu-west-1:783354560127:parameter/Viite/Dev/apiS3BucketName'
          MemoryReservation: 2048
          Image: !Sub '${RepositoryURL}/viite:latest'
          Name: Viite
          HealthCheck:
            StartPeriod: 15
            Command:
              - CMD-SHELL
              - curl -f http://127.0.0.1:9080/api/ping/ || exit 1
      Memory: '4096'
      Family: Viite
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '2048'
      Tags:
        - Key: Name
          Value: Viite-Dev
        - Key: Environment
          Value: Dev
        - Key: Owner
          Value: Vayla
        - Key: Project
          Value: Viite
        - Key: Application
          Value: Viite

Outputs:
  TaskDefinitionArn:
    Description: The ARN of the created task definition
    Value: !Ref Taskdefinition
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefinitionArn'
