AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to set up Cost Anomaly Detection for all resources'

Resources:
  CostAnomalyDetector:
    Type: 'AWS::CE::AnomalyMonitor'
    Properties:
      MonitorName: 'AllServicesCostAnomalyMonitor'
      MonitorType: 'DIMENSIONAL'
      MonitorDimension: 'SERVICE'

  CostAnomalySubscription:
    Type: 'AWS::CE::AnomalySubscription'
    Properties:
      SubscriptionName: 'AllServicesCostAnomalyAlerts'
      ThresholdExpression: '{
       "And": [
          {
            "Dimensions": {
              "Key": "ANOMALY_TOTAL_IMPACT_ABSOLUTE",
              "MatchOptions": [ "GREATER_THAN_OR_EQUAL" ],
              "Values": [ "2" ]
            }
          },
          {
            "Dimensions": {
              "Key": "ANOMALY_TOTAL_IMPACT_PERCENTAGE",
              "MatchOptions": [ "GREATER_THAN_OR_EQUAL" ],
              "Values": [ "100" ]
            }
          }
        ]
      }'
      Frequency: 'DAILY'
      MonitorArnList:
        - !Ref CostAnomalyDetector
      Subscribers:
        - Address: '{{resolve:ssm:/Viite/developerEmail/1}}'
          Type: 'EMAIL'
        - Address: '{{resolve:ssm:/Viite/developerEmail/2}}'
          Type: 'EMAIL'
        - Address: '{{resolve:ssm:/Viite/developerEmail/3}}'
          Type: 'EMAIL'

Outputs:
  AllServicesAnomalyMonitorArn:
    Description: 'ARN of the All Services Cost Anomaly Monitor'
    Value: !GetAtt CostAnomalyDetector.MonitorArn
