AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation managed SecureString Parameters
Parameters:
  Environment:
    Description: "Environment of the application, that these resources are created for. Used when naming the resources"
    Type: String
Resources:
  ConversionDbPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/Viite', !Ref Environment, 'conversion.db.password']]
      Type: String
      Value: PlaceHolderValue
      Description: Password for drkonv db, where the Initial Import data is retrieved

  AuthAdminBasicPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/Viite', !Ref Environment, 'authentication.admin.basic.password']]
      Type: String
      Value: PlaceHolderValue
      Description: Used by the lambdas, to access AdminAPI

  RdsDbPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/Viite', !Ref Environment, 'rds.viite.db.password']]
      Type: String
      Value: PlaceHolderValue
      Description: !Join [' ', ['RDS password for Viite ', !Ref Environment]]

  VkmApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/Viite', !Ref Environment, 'vkmApiKey']]
      Type: String
      Value: PlaceHolderValue
      Description: Viite access key for Viitekehysmuunnin's production API

  RasterServiceApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/Viite', !Ref Environment, 'rasterServiceApiKey']]
      Type: String
      Value: PlaceHolderValue
      Description: Viite access key for Rasteripalvelu-mml hosted in vaylapilvi

  kgvApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/Viite', !Ref Environment, 'kgvApiKey']]
      Type: String
      Value: PlaceHolderValue
      Description: !Join [' ', ['Kgv rest API password for Viite ', !Ref Environment]]
