version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - export CODE_ARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain vayla-viite --domain-owner 783354560127 --region eu-west-1 --query authorizationToken --output text)
      - aws codeartifact login --tool npm --repository viite_npm_packages --domain vayla-viite --domain-owner 783354560127
      - npm config set registry https://vayla-viite-783354560127.d.codeartifact.eu-west-1.amazonaws.com/npm/viite_npm_packages/
      - aws s3 cp s3://fi-viite-dev/sbt/sbt-0.13.18.deb /tmp/sbt-0.13.18.deb
      - sudo dpkg -i /tmp/sbt-0.13.18.deb
      - npm install
      - npm install -g grunt-cli
  pre_build:
    commands:
      - pip install --upgrade awscli
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Helsinki /etc/localtime
  build:
    commands:
      - grunt test
      - sbt ${1} ${2} "project viite-main" "test:run-main fi.liikennevirasto.viite.util.DataFixture flyway_migrate"
      - sbt ${1} ${2} "project viite-main" "test:run-main fi.liikennevirasto.viite.util.DataFixture test"
      - sbt test
      - grunt deploy
      - sbt clean
      - sbt assembly
      - docker build -t viite-ci-build:latest -f aws/fargate/Dockerfile .
      - docker images -a
      - docker tag viite-ci-build:latest $(echo $REPOSITORY_URI):latest
      - echo "Pushing the Docker image"
      - docker push $(echo $REPOSITORY_URI):latest
      - aws ecs update-service --region eu-west-1 --cluster Viite-ECS-Cluster-Private --service Viite-ECS-Service-Private --force-new-deployment
