version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a  /etc/apt/sources.list.d/sbt.list
      - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
      - apt-get update
      - apt-get install sbt
      - npm install
      - npm install -g grunt-cli
  pre_build:
    commands:
      - pip install --upgrade awscli
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Helsinki /etc/localtime
  build:
    commands:
      - grunt test
      - sbt ${1} ${2} "project viite-main" "test:run-main fi.liikennevirasto.viite.util.DataFixture flyway_migrate"
      - sbt ${1} ${2} "project viite-main" "test:run-main fi.liikennevirasto.viite.util.DataFixture test"
      - sbt test
      - grunt deploy
      - sbt clean
      - sbt assembly
      - docker build -t viite-ci-build:latest -f aws/fargate/Dockerfile .
      - docker images -a
      - docker tag viite-ci-build:latest $(echo $REPOSITORY_URI):latest
      - echo "Pushing the Docker image"
      - docker push $(echo $REPOSITORY_URI):latest
      - aws ecs update-service --region eu-west-1 --cluster QA-viite-test-ECS-Cluster-Private --service QA-viite-test-ECS-Service-Private --force-new-deployment
