  CREATE TABLE ROADWAY_POINT
   (	ID NUMBER NOT NULL,
	ROADWAY_NUMBER NUMBER NOT NULL,
	ADDR_M NUMBER NOT NULL,
	VALID_FROM DATE NOT NULL,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL,
	CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT ROADWAY_POINT_UK1 UNIQUE (ROADWAY_NUMBER, ADDR_M),
	 CONSTRAINT ROADWAY_POINT_PK PRIMARY KEY (ID)
   );


  CREATE TABLE NODE
   (	ID NUMBER NOT NULL,
	NODE_NUMBER NUMBER(9,0) NOT NULL,
	COORDINATES SDO_GEOMETRY NOT NULL,
	NAME VARCHAR2(30 BYTE),
	TYPE NUMBER NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	VALID_FROM DATE NOT NULL,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL,
	CREATED_TIME TIMESTAMP (6) NOT NULL,
	 CONSTRAINT NODE_PK PRIMARY KEY (ID)
  );


  CREATE TABLE NODE_POINT
   (	ID NUMBER NOT NULL,
	BEFORE_AFTER NUMBER(1,0) NOT NULL,
	ROADWAY_POINT_ID NUMBER NOT NULL,
	NODE_ID NUMBER NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	VALID_FROM DATE NOT NULL,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL,
	CREATED_TIME TIMESTAMP (6) NOT NULL,
	 CONSTRAINT NODE_POINT_PK PRIMARY KEY (ID),
	 CONSTRAINT NODE_POINT_FK2 FOREIGN KEY (NODE_ID)
	  REFERENCES NODE (ID)
   );

  CREATE TABLE JUNCTION
   (	ID NUMBER NOT NULL,
	JUNCTION_NUMBER NUMBER(2,0) NOT NULL,
	RAMP_NUMBER VARCHAR2(3 BYTE),
	TRAFFIC_LIGHTS NUMBER(2,0),
	NODE_ID NUMBER,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	LIGHTS_START_DATE DATE,
	VALID_FROM DATE NOT NULL,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL,
	CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT JUNCTION_PK PRIMARY KEY (ID)
   );

  CREATE TABLE JUNCTION_POINT
   (	ID NUMBER NOT NULL,
	BEFORE_AFTER NUMBER(1,0) NOT NULL,
	ROADWAY_POINT_ID NUMBER NOT NULL,
	JUNCTION_ID NUMBER NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	VALID_FROM DATE NOT NULL,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL,
	CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT JUNCTION_POINT_CHK1 CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))),
	 CONSTRAINT JUNCTION_POINT_PK PRIMARY KEY (ID),
   CONSTRAINT JUNCTION_POINT_FK1 FOREIGN KEY (JUNCTION_ID)
    REFERENCES JUNCTION (ID)
   );

  CREATE SEQUENCE ROADWAY_POINT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

  CREATE SEQUENCE NODE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

  CREATE SEQUENCE NODE_POINT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

  CREATE SEQUENCE JUNCTION_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

  CREATE SEQUENCE JUNCTION_POINT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;