DROP TABLE "ROAD_ADDRESS";

CREATE TABLE "ROAD_ADDRESS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER NOT NULL ENABLE,
	"ROAD_PART_NUMBER" NUMBER NOT NULL ENABLE,
	"TRACK_CODE" NUMBER NOT NULL ENABLE,
	"DISCONTINUITY" NUMBER NOT NULL ENABLE,
	"START_ADDR_M" NUMBER NOT NULL ENABLE,
	"END_ADDR_M" NUMBER NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CALIBRATION_POINTS" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"FLOATING" CHAR(1) DEFAULT '0',
	"GEOMETRY" "SDO_GEOMETRY",
	"VALID_TO" DATE,
	"ELY" NUMBER,
	"ROAD_TYPE" NUMBER,
	"TERMINATED" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"COMMON_HISTORY_ID" NUMBER(38,0),
	"LANE_CODE" NUMBER(5,0),
	"SIDE_CODE" NUMBER(5,0),
	"START_MEASURE" NUMBER(8,3),
	"END_MEASURE" NUMBER(8,3),
	"LINK_ID" NUMBER(38,0),
	"ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
	"MODIFIED_DATE" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	"LINK_SOURCE" NUMBER(*,0) DEFAULT (1),
	 CONSTRAINT "ROAD_ADDRESS_HISTORY_CHECK" UNIQUE ("ROAD_NUMBER", "ROAD_PART_NUMBER", "START_ADDR_M", "END_ADDR_M", "TRACK_CODE", "DISCONTINUITY", "START_DATE", "END_DATE", "VALID_FROM", "VALID_TO", "ELY", "ROAD_TYPE", "TERMINATED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "CK_TERMINATION_END_DATE" CHECK (TERMINATED = 0 OR (TERMINATED in (1,2) AND END_DATE IS NOT NULL)) ENABLE,
	 CONSTRAINT "RA_FLOATING_IS_BOOLEAN" CHECK (floating in ('1','0')) ENABLE,
	 CONSTRAINT "ROAD_ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

CREATE INDEX "ROAD_ADDRESS_FLOATING_IDX" ON "ROAD_ADDRESS" ("FLOATING")
TABLESPACE "USERS";

CREATE INDEX "ROAD_ADDRESS_GEOMETRY_SX" ON "ROAD_ADDRESS" ("GEOMETRY")
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX";

CREATE INDEX "ROAD_ADDRESS_ADDR" ON "ROAD_ADDRESS" ("ROAD_NUMBER", "ROAD_PART_NUMBER", "TRACK_CODE")
TABLESPACE "USERS";

CREATE UNIQUE INDEX "ROAD_ADDRESS_PK" ON "ROAD_ADDRESS" ("ID")
TABLESPACE "USERS";

CREATE INDEX "ROAD_ADDRESS_LINK_ID_IDX" ON "ROAD_ADDRESS" ("LINK_ID")
TABLESPACE "USERS" ;

DROP TABLE "PROJECT_LINK";

CREATE TABLE "PROJECT_LINK"
   (	"ID" NUMBER NOT NULL ENABLE,
	"PROJECT_ID" NUMBER NOT NULL ENABLE,
	"TRACK_CODE" NUMBER NOT NULL ENABLE,
	"DISCONTINUITY_TYPE" NUMBER DEFAULT 5 NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER CONSTRAINT "ROAD_NOT_NULL" NOT NULL ENABLE,
	"ROAD_PART_NUMBER" NUMBER CONSTRAINT "PART_NOT_NULL" NOT NULL ENABLE,
	"START_ADDR_M" NUMBER,
	"END_ADDR_M" NUMBER,
	"LRM_POSITION_ID" NUMBER NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(32),
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"MODIFIED_DATE" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	"STATUS" NUMBER,
	"CALIBRATION_POINTS" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"ROAD_TYPE" NUMBER DEFAULT 99 NOT NULL ENABLE,
	"ROAD_ADDRESS_ID" NUMBER,
	"CONNECTED_LINK_ID" NUMBER,
	"ELY" NUMBER,
	"REVERSED" NUMBER(1,0) DEFAULT 0,
	"GEOMETRY" VARCHAR2(4000) DEFAULT NULL,
	"LANE_CODE" NUMBER(5,0),
	"SIDE_CODE" NUMBER(5,0),
	"START_MEASURE" NUMBER(8,3),
	"END_MEASURE" NUMBER(8,3),
	"LINK_ID" NUMBER(38,0),
	"ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
	"LINK_SOURCE" NUMBER(*,0) DEFAULT (1)
	 CONSTRAINT "PROJECT_LINK_ADDRESS_CHK1" CHECK ((road_number is null and road_part_number is null) or
(road_number is not null and road_part_number is not null and start_addr_m is not null and end_addr_m is not null)) ENABLE,
	 CONSTRAINT "PROJECT_LINK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_LINK_RESERVED" FOREIGN KEY ("PROJECT_ID", "ROAD_NUMBER", "ROAD_PART_NUMBER")
	  REFERENCES "PROJECT_RESERVED_ROAD_PART" ("PROJECT_ID", "ROAD_NUMBER", "ROAD_PART_NUMBER") ENABLE,
	 CONSTRAINT "PROJECT_LINK_PROJECT_ID_FK1" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ON DELETE CASCADE ENABLE,
	 FOREIGN KEY ("ROAD_ADDRESS_ID")
	  REFERENCES "ROAD_ADDRESS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

CREATE INDEX "PROJECT_LINK_LINK_ID_IDX" ON "PROJECT_LINK" ("LINK_ID")
TABLESPACE "USERS";

CREATE INDEX "PROJECT_LINK_PRJ_IDX" ON "PROJECT_LINK" ("PROJECT_ID")
TABLESPACE "USERS" ;

CREATE INDEX "PROJECT_LINK_CONNECT_IDX" ON "PROJECT_LINK" ("CONNECTED_LINK_ID")
TABLESPACE "USERS" ;

CREATE INDEX "PLINK_ROAD_ADDRESS_IDX" ON "PROJECT_LINK" ("ROAD_ADDRESS_ID")
TABLESPACE "USERS" ;

DROP TABLE "PROJECT_LINK_HISTORY";

CREATE TABLE "PROJECT_LINK_HISTORY"
   (	"ID" NUMBER NOT NULL ENABLE,
	"PROJECT_ID" NUMBER NOT NULL ENABLE,
	"TRACK_CODE" NUMBER NOT NULL ENABLE,
	"DISCONTINUITY_TYPE" NUMBER DEFAULT 5 NOT NULL ENABLE,
	"ROAD_NUMBER" NUMBER,
	"ROAD_PART_NUMBER" NUMBER,
	"START_ADDR_M" NUMBER,
	"END_ADDR_M" NUMBER,
	"CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(32),
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"MODIFIED_DATE" DATE,
	"STATUS" NUMBER,
	"CALIBRATION_POINTS" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"ROAD_TYPE" NUMBER DEFAULT 99 NOT NULL ENABLE,
	"LANE_CODE" NUMBER(5,0),
	"SIDE_CODE" NUMBER(5,0),
	"START_MEASURE" NUMBER(8,3),
	"END_MEASURE" NUMBER(8,3),
	"LINK_ID" NUMBER(38,0),
	"ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
	"LINK_SOURCE" NUMBER(*,0) DEFAULT (1),
	 CONSTRAINT "PROJECT_LINK_HIST_PROJECT_FK1" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

CREATE INDEX "PROJECT_LINK_HIST_PRJ_IDX" ON "PROJECT_LINK_HISTORY" ("PROJECT_ID")
TABLESPACE "USERS" ;

CREATE INDEX "PROJECT_LINK_HIST_ROAD_IDX" ON "PROJECT_LINK_HISTORY" ("ROAD_NUMBER", "ROAD_PART_NUMBER")
TABLESPACE "USERS" ;

DROP TABLE "LRM_POSITION";
DROP SEQUENCE "LRM_POSITION_PRIMARY_KEY_SEQ";
