ALTER TABLE "ROAD_ADDRESS"
    ADD CONSTRAINT "ROAD_ADDRESS_DUPLICATE" UNIQUE ( road_number,
                                                     road_part_number,
                                                     track_code,
                                                     discontinuity,
                                                     start_addr_m,
                                                     end_addr_m,
                                                     start_date,
                                                     NVL(end_date,'NULL'),
                                                     valid_from,
                                                     NVL(valid_to,'NULL'),
                                                     calibration_points,
                                                     floating,
                                                     ely,
                                                     road_type,
                                                     terminated,
                                                     common_history_id,
                                                     side_code,
                                                     start_measure,
                                                     end_measure,
                                                     link_id,
                                                     link_source );