--------------------------------------------------------
--  Removing table PROJECT_LINK_HISTORY
--------------------------------------------------------

DROP TABLE "PROJECT_LINK_HISTORY";

--------------------------------------------------------
--  Recreating PROJECT_LINK_HISTORY
--------------------------------------------------------

CREATE TABLE "PROJECT_LINK_HISTORY"
(
  "ID" NUMBER,
	"PROJECT_ID" NUMBER,
	"TRACK_CODE" NUMBER,
	"DISCONTINUITY_TYPE" NUMBER DEFAULT 5,
	"ROAD_NUMBER" NUMBER,
	"ROAD_PART_NUMBER" NUMBER,
	"START_ADDR_M" NUMBER,
	"END_ADDR_M" NUMBER,
	"CREATED_BY" VARCHAR2(32 BYTE),
	"MODIFIED_BY" VARCHAR2(32 BYTE),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"MODIFIED_DATE" DATE,
	"STATUS" NUMBER,
	"CALIBRATION_POINTS" NUMBER DEFAULT 0,
	"ROAD_TYPE" NUMBER DEFAULT 99,
	"ROAD_ADDRESS_ID" NUMBER,
	"CONNECTED_LINK_ID" NUMBER,
	"ELY" NUMBER,
	"REVERSED" NUMBER(1,0) DEFAULT 0,
	"GEOMETRY" VARCHAR2(4000 BYTE) DEFAULT NULL,
	"SIDE_CODE" NUMBER(5,0),
  "START_MEASURE" NUMBER(8,3),
  "END_MEASURE" NUMBER(8,3),
  "LINK_ID" NUMBER(38,0),
  "ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
  "LINK_SOURCE" NUMBER(*,0) DEFAULT (1),
	"CALIBRATION_POINTS_SOURCE" NUMBER DEFAULT 0
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  Ref Constraints for Table PROJECT_LINK_HISTORY
--------------------------------------------------------

ALTER TABLE "PROJECT_LINK_HISTORY" ADD CONSTRAINT "PROJECT_LINK_HIST_PROJECT_FK1" FOREIGN KEY ("PROJECT_ID")
  REFERENCES "PROJECT" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Creating INDEXES for PROJECT_LINK_HISTORY
--------------------------------------------------------

--------------------------------------------------------
--  Index PROJECT_LINK_HIST_PRJ_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_LINK_HIST_PRJ_IDX" ON "PROJECT_LINK_HISTORY" ("PROJECT_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  Index PROJECT_LINK_HIST_ROAD_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_LINK_HIST_ROAD_IDX" ON "PROJECT_LINK_HISTORY" ("ROAD_NUMBER", "ROAD_PART_NUMBER")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  Constraints for Table PROJECT_LINK_HISTORY
--------------------------------------------------------

ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("ROAD_TYPE" NOT NULL ENABLE);
ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("CALIBRATION_POINTS" NOT NULL ENABLE);
ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("CREATED_BY" NOT NULL ENABLE);
ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("DISCONTINUITY_TYPE" NOT NULL ENABLE);
ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("TRACK_CODE" NOT NULL ENABLE);
ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
ALTER TABLE "PROJECT_LINK_HISTORY" MODIFY ("ID" NOT NULL ENABLE);