ALTER TABLE LINEAR_LOCATION ADD (CAL_START NUMBER);
ALTER TABLE LINEAR_LOCATION ADD (CAL_END NUMBER);
ALTER TABLE LINEAR_LOCATION ADD (CAL_START_SOURCE NUMBER(2,0) DEFAULT 0);
ALTER TABLE LINEAR_LOCATION ADD (CAL_END_SOURCE NUMBER(2,0) DEFAULT 0);
ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT CAL_START_FK FOREIGN KEY (CAL_START) REFERENCES ROADWAY_POINT (ID);
ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT CAL_END_FK FOREIGN KEY (CAL_END) REFERENCES ROADWAY_POINT (ID);
