ALTER TABLE LINEAR_LOCATION DROP CONSTRAINT LINEAR_LOCATION_UK;
ALTER TABLE LINEAR_LOCATION DROP COLUMN CAL_START_ADDR_M;
ALTER TABLE LINEAR_LOCATION DROP COLUMN CAL_END_ADDR_M;
ALTER TABLE LINEAR_LOCATION ADD (CAL_START NUMBER);
ALTER TABLE LINEAR_LOCATION ADD (CAL_END NUMBER);
ALTER TABLE LINEAR_LOCATION ADD (CAL_START_LOCKED NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE LINEAR_LOCATION ADD (CAL_END_LOCKED NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT CAL_START_FK FOREIGN KEY (CAL_START) REFERENCES ROADWAY_POINT (ID);
ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT CAL_END_FK FOREIGN KEY (CAL_END) REFERENCES ROADWAY_POINT (ID);
ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT LINEAR_LOCATION_UK UNIQUE (ROADWAY_NUMBER, ORDER_NUMBER, LINK_ID, START_MEASURE, END_MEASURE,
    VALID_TO, CAL_START, CAL_END, FLOATING, SIDE, LINK_SOURCE) USING INDEX;
