ALTER TABLE "ROAD_ADDRESS"
  DROP COLUMN "LRM_POSITION_ID"
;
ALTER TABLE "ROAD_ADDRESS"
  ADD (
    "SIDE_CODE" NUMBER(5,0),
    "START_MEASURE" NUMBER(8,3),
    "END_MEASURE" NUMBER(8,3),
    "LINK_ID" NUMBER(38,0),
    "ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
    "MODIFIED_DATE" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
    "LINK_SOURCE" NUMBER(*,0) DEFAULT (1)
  )
;

CREATE INDEX "ROAD_ADDRESS_LINK_ID_IDX" ON "ROAD_ADDRESS" ("LINK_ID")
TABLESPACE "USERS" ;

ALTER TABLE "PROJECT_LINK"
  DROP COLUMN "LRM_POSITION_ID"
;
ALTER TABLE "PROJECT_LINK"
  ADD (
    "SIDE_CODE" NUMBER(5,0),
    "START_MEASURE" NUMBER(8,3),
    "END_MEASURE" NUMBER(8,3),
    "LINK_ID" NUMBER(38,0),
    "ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
    "LINK_SOURCE" NUMBER(*,0) DEFAULT (1)
  )
;

CREATE INDEX "PROJECT_LINK_LINK_ID_IDX" ON "PROJECT_LINK" ("LINK_ID")
TABLESPACE "USERS";

ALTER TABLE "PROJECT_LINK_HISTORY"
  DROP COLUMN "LRM_POSITION_ID"
;
ALTER TABLE "PROJECT_LINK_HISTORY"
  ADD (
    "SIDE_CODE" NUMBER(5,0),
    "START_MEASURE" NUMBER(8,3),
    "END_MEASURE" NUMBER(8,3),
    "LINK_ID" NUMBER(38,0),
    "ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
    "LINK_SOURCE" NUMBER(*,0) DEFAULT (1)
  )
;

DROP TABLE "LRM_POSITION";
DROP SEQUENCE "LRM_POSITION_PRIMARY_KEY_SEQ";
