CREATE EXTENSION postgis SCHEMA public;

CREATE SEQUENCE PROJECT_CAL_POINT_ID_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NO CYCLE;

CREATE SEQUENCE ROADWAY_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 100 CYCLE;

CREATE SEQUENCE LINEAR_LOCATION_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 100 CYCLE;

CREATE SEQUENCE ROADWAY_NUMBER_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 300000000 CACHE 20 NO CYCLE;

CREATE SEQUENCE SERVICE_USER_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 35000000 CACHE 100 CYCLE;

CREATE SEQUENCE PROJECT_LINK_NAME_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NO CYCLE;

CREATE SEQUENCE PUBLISHED_ROAD_NETWORK_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 101 CACHE 100 CYCLE;

CREATE SEQUENCE ROAD_NAME_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 50000 CACHE 10 NO CYCLE;

CREATE SEQUENCE ROAD_NETWORK_ERROR_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 100 CYCLE;

CREATE SEQUENCE VIITE_GENERAL_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 6158121 CACHE 20 NO CYCLE;

CREATE SEQUENCE VIITE_PROJECT_SEQ MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 464783 NO CYCLE;
