ALTER TABLE Road_Network_Errors ADD CONSTRAINT "UNIQUE_ADDRESS_ERROR_VERSION" UNIQUE ("ROAD_ADDRESS_ID", "ERROR_CODE", "ROAD_NETWORK_VERSION")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE;