  CREATE TABLE ROADWAY_POINT
   (	ID NUMBER NOT NULL ENABLE,
	ROADWAY_NUMBER NUMBER NOT NULL ENABLE,
	ADDR_M NUMBER NOT NULL ENABLE,
	VALID_FROM DATE NOT NULL ENABLE,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL ENABLE,
	CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT ROADWAY_POINT_UK1 UNIQUE (ROADWAY_NUMBER, ADDR_M)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE USERS  ENABLE,
	 CONSTRAINT ROADWAY_POINT_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;


  CREATE TABLE NODE
   (	ID NUMBER NOT NULL ENABLE,
	NODE_NUMBER NUMBER(9,0) NOT NULL ENABLE,
	COORDINATES SDO_GEOMETRY NOT NULL ENABLE,
	NAME VARCHAR2(30 BYTE),
	TYPE NUMBER NOT NULL ENABLE,
	START_DATE DATE NOT NULL ENABLE,
	END_DATE DATE,
	VALID_FROM DATE NOT NULL ENABLE,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL ENABLE,
	CREATED_TIME TIMESTAMP (6) NOT NULL ENABLE,
	 CONSTRAINT NODE_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;


  CREATE TABLE NODE_POINT
   (	ID NUMBER NOT NULL ENABLE,
	BEFORE_AFTER NUMBER(1,0) NOT NULL ENABLE,
	ROADWAY_POINT_ID NUMBER NOT NULL ENABLE,
	NODE_ID NUMBER NOT NULL ENABLE,
	START_DATE DATE NOT NULL ENABLE,
	END_DATE DATE,
	VALID_FROM DATE NOT NULL ENABLE,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL ENABLE,
	CREATED_TIME TIMESTAMP (6) NOT NULL ENABLE,
	 CONSTRAINT NODE_POINT_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE USERS  ENABLE,
	 CONSTRAINT NODE_POINT_FK1 FOREIGN KEY (ROADWAY_POINT_ID)
	  REFERENCES ROADWAY_POINT (ID) ENABLE,
	 CONSTRAINT NODE_POINT_FK2 FOREIGN KEY (NODE_ID)
	  REFERENCES NODE (ID) ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;

  CREATE TABLE JUNCTION
   (	ID NUMBER NOT NULL ENABLE,
	JUNCTION_NUMBER NUMBER(2,0) NOT NULL ENABLE,
	RAMP_NUMBER VARCHAR2(3 BYTE),
	TRAFFIC_LIGHTS NUMBER(2,0),
	NODE_ID NUMBER,
	START_DATE DATE NOT NULL ENABLE,
	END_DATE DATE,
	LIGHTS_START_DATE DATE,
	VALID_FROM DATE NOT NULL ENABLE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL ENABLE,
	CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT JUNCTION_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;

  CREATE TABLE JUNCTION_POINT
   (	ID NUMBER NOT NULL ENABLE,
	BEFORE_AFTER NUMBER(1,0) NOT NULL ENABLE,
	ROADWAY_POINT_ID NUMBER NOT NULL ENABLE,
	JUNCTION_ID NUMBER NOT NULL ENABLE,
	START_DATE DATE NOT NULL ENABLE,
	END_DATE DATE,
	VALID_FROM DATE NOT NULL ENABLE,
	VALID_TO DATE,
	CREATED_BY VARCHAR2(32 BYTE) NOT NULL ENABLE,
	CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE,
	 CONSTRAINT JUNCTION_POINT_CHK1 CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))) ENABLE,
	 CONSTRAINT JUNCTION_POINT_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
