CREATE INDEX CALIBRATION_POINT_I ON CALIBRATION_POINT(ROADWAY_POINT_ID);

CREATE INDEX CALIBRATION_POINT_II ON CALIBRATION_POINT(ROADWAY_POINT_ID, LINK_ID, START_END);

CREATE INDEX CALIBRATION_POINT_III ON CALIBRATION_POINT(LINK_ID, START_END);

CREATE INDEX LOCATION_I ON LINEAR_LOCATION(ID, ROADWAY_NUMBER, LINK_ID, START_MEASURE, END_MEASURE, SIDE, VALID_FROM, VALID_TO);

CREATE INDEX LINK_I ON LINK(ID, SOURCE, ADJUSTED_TIMESTAMP);