ALTER TABLE LINEAR_LOCATION DROP CONSTRAINT LINEAR_LOCATION_UK;
ALTER TABLE LINEAR_LOCATION DROP COLUMN CAL_START_ADDR_M;
ALTER TABLE LINEAR_LOCATION DROP COLUMN CAL_END_ADDR_M;
ALTER TABLE LINEAR_LOCATION DROP COLUMN LINK_SOURCE;
ALTER TABLE LINEAR_LOCATION DROP COLUMN ADJUSTED_TIMESTAMP;
ALTER TABLE LINEAR_LOCATION RENAME COLUMN CREATE_TIME TO CREATED_TIME;
ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT LINEAR_LOCATION_UK UNIQUE (ROADWAY_NUMBER, ORDER_NUMBER, LINK_ID, START_MEASURE, END_MEASURE, VALID_TO, SIDE);

ALTER TABLE ROADWAY RENAME COLUMN CREATE_TIME TO CREATED_TIME;

ALTER TABLE junction ADD COLUMN VALID_TO DATE;
ALTER TABLE junction ADD CONSTRAINT fk_junction_node_id FOREIGN KEY (node_id) REFERENCES node(id);

CREATE TABLE LINK (
  ID BIGINT NOT NULL,
  SOURCE SMALLINT DEFAULT 1 NOT NULL,
  ADJUSTED_TIMESTAMP NUMERIC(13,0) DEFAULT 0 NOT NULL,
  CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
  CONSTRAINT LINK_PK PRIMARY KEY (ID)
);

ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT linear_location_link_fk FOREIGN KEY (link_id) REFERENCES link(id);

CREATE TABLE CALIBRATION_POINT (
  ID BIGINT NOT NULL,
  ROADWAY_POINT_ID BIGINT NOT NULL,
  LINK_ID BIGINT NOT NULL,
  START_END SMALLINT DEFAULT 0 NOT NULL, -- 0 = start, 1 = end
  TYPE SMALLINT DEFAULT 0 NOT NULL,
  VALID_FROM DATE DEFAULT current_date NOT NULL,
  VALID_TO DATE,
  CREATED_BY VARCHAR(32) NOT NULL,
  CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
  CONSTRAINT CALIBRATION_POINT_PK PRIMARY KEY (ID),
  CONSTRAINT CP_ROADWAY_POINT_FK FOREIGN KEY (ROADWAY_POINT_ID) REFERENCES ROADWAY_POINT (ID),
  CONSTRAINT CP_LINK_FK FOREIGN KEY (LINK_ID) REFERENCES LINK (ID),
  CONSTRAINT CP_START_END_CHK CHECK (START_END in (0,1)),
  CONSTRAINT CP_TYPE_CHK CHECK (TYPE in (0,1,2)) -- 0 = in the middle of roadway, 1 = at the end of roadway but not compulsory, 2 = compulsory
);

CREATE SEQUENCE CALIBRATION_POINT_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 10000 CACHE 20 NO CYCLE;

ALTER TABLE NODE DROP COLUMN VALID_FROM;
ALTER TABLE NODE ADD COLUMN VALID_FROM DATE DEFAULT current_date NOT NULL;
ALTER TABLE JUNCTION DROP COLUMN VALID_FROM;
ALTER TABLE JUNCTION ADD COLUMN VALID_FROM DATE DEFAULT current_date NOT NULL;
