ALTER TABLE LINEAR_LOCATION DROP CONSTRAINT LINEAR_LOCATION_UK;
ALTER TABLE LINEAR_LOCATION DROP COLUMN CAL_START_ADDR_M;
ALTER TABLE LINEAR_LOCATION DROP COLUMN CAL_END_ADDR_M;
ALTER TABLE LINEAR_LOCATION ADD CONSTRAINT LINEAR_LOCATION_UK UNIQUE (ROADWAY_NUMBER, ORDER_NUMBER, LINK_ID, START_MEASURE, END_MEASURE,
    VALID_TO, FLOATING, SIDE, LINK_SOURCE) USING INDEX;

ALTER TABLE junction ADD (VALID_TO DATE);
ALTER TABLE junction ADD CONSTRAINT fk_junction_node_id FOREIGN KEY (node_id) REFERENCES node(id);

CREATE TABLE CALIBRATION_POINT (
  ID NUMBER NOT NULL,
  ROADWAY_POINT_ID NUMBER NOT NULL,
  LINEAR_LOCATION_ID NUMBER NOT NULL,
  START_END NUMBER(1,0) DEFAULT 0 NOT NULL,
  TYPE NUMBER(2,0) DEFAULT 0 NOT NULL,
  VALID_FROM DATE DEFAULT sysdate NOT NULL,
  VALID_TO DATE,
  CREATED_BY VARCHAR2(32) NOT NULL,
  CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
  CONSTRAINT CALIBRATION_POINT_PK PRIMARY KEY (ID),
  CONSTRAINT CP_ROADWAY_POINT_FK FOREIGN KEY (ROADWAY_POINT_ID) REFERENCES ROADWAY_POINT (ID),
  CONSTRAINT CP_LINEAR_LOCATION_FK FOREIGN KEY (LINEAR_LOCATION_ID) REFERENCES LINEAR_LOCATION (ID),
  CONSTRAINT CP_START_END_CHK CHECK (START_END in (0,1)),
  CONSTRAINT CP_TYPE_CHK CHECK (TYPE in (0,1,2)) -- 0 = in the middle of roadway, 1 = at the end of roadway but not compulsory, 2 = compulsory
);

-- TODO make nodes and junction table's valid_from: "VALID_FROM DATE DEFAULT sysdate NOT NULL,"
