ALTER TABLE ROADWAY_CHANGES ADD COLUMN ROADWAY_CHANGE_ID INTEGER NOT NULL;

CREATE SEQUENCE ROADWAY_CHANGE_LINK MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NO CYCLE;

CREATE TABLE ROADWAY_CHANGES_LINK(
  ROADWAY_CHANGE_ID INTEGER NOT NULL,
  PROJECT_ID BIGINT NOT NULL,
  PROJECT_LINK_ID BIGINT NOT NULL,
  CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
  CONSTRAINT PROJECT_LINK_FK FOREIGN KEY (PROJECT_LINK_ID) REFERENCES PROJECT_LINK (ID)
);
