CREATE TABLE ROADWAY_POINT (
  ID BIGINT NOT NULL,
  ROADWAY_NUMBER BIGINT NOT NULL,
  ADDR_M INTEGER NOT NULL,
  CREATED_BY VARCHAR(32) NOT NULL,
  CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
  MODIFIED_BY VARCHAR(32) NOT NULL,
  MODIFIED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
  CONSTRAINT ROADWAY_POINT_UK1 UNIQUE (ROADWAY_NUMBER, ADDR_M),
  CONSTRAINT ROADWAY_POINT_PK PRIMARY KEY (ID)
);

CREATE TABLE NODE (
  ID BIGINT NOT NULL,
  NODE_NUMBER BIGINT NOT NULL,
  COORDINATES GEOMETRY NOT NULL,
  NAME VARCHAR(30),
  TYPE SMALLINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  VALID_FROM DATE NOT NULL,
  VALID_TO DATE,
  CREATED_BY VARCHAR(32) NOT NULL,
  CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
  CONSTRAINT NODE_PK PRIMARY KEY (ID)
);

CREATE TABLE NODE_POINT (
  ID BIGINT NOT NULL,
  BEFORE_AFTER SMALLINT NOT NULL,
  ROADWAY_POINT_ID BIGINT NOT NULL,
  NODE_ID BIGINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  VALID_FROM DATE NOT NULL,
  VALID_TO DATE,
  CREATED_BY VARCHAR(32) NOT NULL,
  CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
  CONSTRAINT NODE_POINT_CHK1 CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))),
  CONSTRAINT NODE_POINT_PK PRIMARY KEY (ID),
  CONSTRAINT NODE_POINT_FK2 FOREIGN KEY (NODE_ID)
    REFERENCES NODE (ID)
);

CREATE TABLE JUNCTION (
  ID BIGINT NOT NULL,
  JUNCTION_NUMBER SMALLINT NOT NULL,
  RAMP_NUMBER VARCHAR(3),
  TRAFFIC_LIGHTS SMALLINT,
  NODE_ID BIGINT,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  LIGHTS_START_DATE DATE,
  VALID_FROM DATE NOT NULL,
  CREATED_BY VARCHAR(32) NOT NULL,
  CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
  CONSTRAINT JUNCTION_PK PRIMARY KEY (ID)
);

CREATE TABLE JUNCTION_POINT (
  ID BIGINT NOT NULL,
  BEFORE_AFTER SMALLINT NOT NULL,
  ROADWAY_POINT_ID BIGINT NOT NULL,
  JUNCTION_ID BIGINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  VALID_FROM DATE NOT NULL,
  VALID_TO DATE,
  CREATED_BY VARCHAR(32) NOT NULL,
  CREATED_TIME TIMESTAMP (6) DEFAULT current_timestamp NOT NULL,
  CONSTRAINT JUNCTION_POINT_CHK1 CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))),
  CONSTRAINT JUNCTION_POINT_PK PRIMARY KEY (ID),
  CONSTRAINT JUNCTION_POINT_FK1 FOREIGN KEY (JUNCTION_ID)
    REFERENCES JUNCTION (ID)
);

CREATE SEQUENCE ROADWAY_POINT_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 10000 CACHE 20 NO CYCLE;

CREATE SEQUENCE NODE_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 10000 CACHE 20 NO CYCLE;

CREATE SEQUENCE NODE_POINT_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 10000 CACHE 20 NO CYCLE;

CREATE SEQUENCE JUNCTION_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 10000 CACHE 20 NO CYCLE;

CREATE SEQUENCE JUNCTION_POINT_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 10000 CACHE 20 NO CYCLE;
