ALTER TABLE road_address
    ADD CONSTRAINT road_address_duplicate UNIQUE ( road_number,
                                                   road_part_number,
                                                   track_code,
                                                   discontinuity,
                                                   start_addr_m,
                                                   end_addr_m,
                                                   start_date,
                                                   end_date,
                                                   valid_to,
                                                   calibration_points,
                                                   floating,
                                                   ely,
                                                   road_type,
                                                   terminated,
                                                   common_history_id,
                                                   side_code,
                                                   start_measure,
                                                   end_measure,
                                                   link_id,
                                                   link_source );