CREATE TABLE PROJECT_ACTION_HISTORY (
    PROJECT_ID BIGINT NOT NULL,
    ACTION_TYPE VARCHAR(32) NOT NULL,
    PAYLOAD VARCHAR,
    CREATED_BY VARCHAR(128),
    CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
    CONSTRAINT PROJECT_ACTION_HISTORY_PROJECT_FK FOREIGN KEY (PROJECT_ID)
        REFERENCES PROJECT (ID)
);

CREATE INDEX PLACEHOLDER_PROJECT_ID_TIMESTAMP_I ON PROJECT_ACTION_HISTORY (PROJECT_ID, CREATED_TIME);
