CREATE SEQUENCE LINK_ID_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

ALTER TABLE LINK ADD (UUID VARCHAR2(36) NOT NULL);
ALTER TABLE LINK ADD (VERSION NUMBER(8,0) NOT NULL);

ALTER TABLE LINK ADD CONSTRAINT LINK_UUID_VERSION_UK UNIQUE (UUID, VERSION) USING INDEX;

ALTER TABLE PROJECT_LINK ADD CONSTRAINT fk_pl_link_id FOREIGN KEY (link_id) REFERENCES link(id);
