ALTER TABLE "PROJECT_LINK" RENAME COLUMN GEOMETRY TO GEOMETRY_STRING;
ALTER TABLE "PROJECT_LINK" ADD (GEOMETRY SDO_GEOMETRY);

ALTER TABLE "PROJECT_LINK_HISTORY" RENAME COLUMN GEOMETRY TO GEOMETRY_STRING;
ALTER TABLE "PROJECT_LINK_HISTORY" ADD (GEOMETRY SDO_GEOMETRY);