ALTER TABLE NODE_POINT ADD (NODE_NUMBER NUMBER);
UPDATE NODE_POINT NP SET NP.NODE_NUMBER = (SELECT NODE.NODE_NUMBER FROM NODE NODE WHERE NODE.ID = NP.NODE_ID);
ALTER TABLE NODE_POINT DROP COLUMN NODE_ID;

ALTER TABLE JUNCTION ADD (NODE_NUMBER NUMBER);
UPDATE JUNCTION J SET J.NODE_NUMBER = (SELECT NODE.NODE_NUMBER FROM NODE NODE WHERE NODE.ID = J.NODE_ID);
ALTER TABLE JUNCTION DROP COLUMN NODE_ID;

ALTER TABLE NODE_POINT DROP COLUMN START_DATE;
ALTER TABLE NODE_POINT DROP COLUMN END_DATE;
ALTER TABLE JUNCTION_POINT DROP COLUMN START_DATE;
ALTER TABLE JUNCTION_POINT DROP COLUMN END_DATE;

ALTER TABLE NODE_POINT ADD ("TYPE" NUMBER DEFAULT 99 NOT NULL);

-- TODO NEEDS TO BE INCLUDED ROAD_TYPE CHANGES CONDITION
UPDATE NODE_POINT NP SET "TYPE" = (SELECT CASE
-- [TYPE = 99] Includes templates, expired points or points yet attached to expired nodes
		WHEN (point.NODE_NUMBER IS NULL OR point.VALID_TO IS NOT NULL
		  OR NOT EXISTS (SELECT 1 FROM NODE node
		    WHERE node.NODE_NUMBER = point.NODE_NUMBER
		    AND (node.END_DATE IS NULL AND node.VALID_TO IS NULL))) THEN 99
-- [TYPE = 1] Includes points where ADDR_M is equal to START_ADDR_M or END_ADDR_M of the road (road_number, road_part_number and track)
		WHEN (rp.ADDR_M = (SELECT MIN(roadAddr.START_ADDR_M) FROM ROADWAY roadAddr
				WHERE roadAddr.ROAD_NUMBER = rw.ROAD_NUMBER AND roadAddr.TRACK = rw.TRACK AND roadAddr.ROAD_PART_NUMBER = rw.ROAD_PART_NUMBER
				AND roadAddr.VALID_TO IS NULL AND roadAddr.END_DATE IS NULL)
			OR rp.ADDR_M = (SELECT MAX(roadAddr.END_ADDR_M) FROM ROADWAY roadAddr
				WHERE roadAddr.ROAD_NUMBER = rw.ROAD_NUMBER AND roadAddr.TRACK = rw.TRACK AND roadAddr.ROAD_PART_NUMBER = rw.ROAD_PART_NUMBER
				AND roadAddr.VALID_TO IS NULL AND roadAddr.END_DATE IS NULL)) THEN 1
-- [TYPE = 2]
		ELSE 2
	END AS NODE_POINT_TYPE
	FROM NODE_POINT point
	LEFT JOIN ROADWAY_POINT rp ON point.ROADWAY_POINT_ID = rp.ID
	LEFT JOIN ROADWAY rw ON rp.ROADWAY_NUMBER = rw.ROADWAY_NUMBER AND rw.VALID_TO IS NULL AND rw.END_DATE IS NULL
		WHERE point.ID = NP.ID);