-- TODO Postgres style
--CREATE INDEX NODE_GEOMETRY_I ON NODE (COORDINATES) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX NODE_NUMBER_I ON NODE (NODE_NUMBER);

CREATE SEQUENCE NODE_NUMBER_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;

CREATE SEQUENCE JUNCTION_NUMBER_SEQ MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;

ALTER TABLE NODE_POINT ALTER COLUMN NODE_ID DROP NOT NULL;

ALTER TABLE NODE_POINT ALTER COLUMN VALID_FROM SET DEFAULT current_date;

ALTER TABLE JUNCTION ALTER COLUMN VALID_FROM SET DEFAULT current_date;

ALTER TABLE JUNCTION_POINT ALTER COLUMN VALID_FROM SET DEFAULT current_date;
