CREATE TABLE ROADWAY (
  ID BIGINT NOT NULL,
  ROADWAY_NUMBER BIGINT NOT NULL,
  ROAD_NUMBER INTEGER NOT NULL,
  ROAD_PART_NUMBER INTEGER NOT NULL,
  TRACK SMALLINT NOT NULL,
  START_ADDR_M INTEGER NOT NULL,
  END_ADDR_M INTEGER NOT NULL,
  REVERSED SMALLINT NOT NULL,
  DISCONTINUITY SMALLINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  CREATED_BY VARCHAR(32) NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
  ROAD_TYPE SMALLINT NOT NULL,
  ELY SMALLINT,
  TERMINATED SMALLINT DEFAULT 0 NOT NULL,
  VALID_FROM DATE DEFAULT current_date NOT NULL,
  VALID_TO DATE,
  CONSTRAINT ROADWAY_PK PRIMARY KEY (ID),
  CONSTRAINT ROADWAY_HISTORY_UK UNIQUE (ROAD_NUMBER, ROAD_PART_NUMBER, START_ADDR_M, END_ADDR_M,
    TRACK, DISCONTINUITY, START_DATE, END_DATE, VALID_FROM, VALID_TO, ELY, ROAD_TYPE, TERMINATED),
  CONSTRAINT TERMINATION_END_DATE_CHK CHECK (TERMINATED = 0 OR (TERMINATED in (1,2) AND END_DATE IS NOT NULL))
);

CREATE TABLE LINEAR_LOCATION (
  ID BIGINT NOT NULL,
  ROADWAY_NUMBER BIGINT NOT NULL,
  ORDER_NUMBER INTEGER DEFAULT 0 NOT NULL,
  LINK_ID BIGINT,
  START_MEASURE NUMERIC(8,3),
  END_MEASURE NUMERIC(8,3),
  SIDE SMALLINT,
  CAL_START_ADDR_M INTEGER,
  CAL_END_ADDR_M INTEGER,
  LINK_SOURCE SMALLINT DEFAULT 1,
  ADJUSTED_TIMESTAMP NUMERIC(13,0) DEFAULT 0 NOT NULL,
  FLOATING SMALLINT DEFAULT 0,
  GEOMETRY GEOMETRY,
  VALID_FROM DATE DEFAULT current_date NOT NULL,
  VALID_TO DATE,
  CREATED_BY VARCHAR(128),
  CREATE_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
  CONSTRAINT LINEAR_LOCATION_PK PRIMARY KEY (ID),
  CONSTRAINT LINEAR_LOCATION_UK UNIQUE (ROADWAY_NUMBER, ORDER_NUMBER, LINK_ID, START_MEASURE, END_MEASURE,
    VALID_TO, CAL_START_ADDR_M, CAL_END_ADDR_M, FLOATING, SIDE, LINK_SOURCE)
);

CREATE TABLE EXPORT_LOCK (
  ID SMALLINT NOT NULL, 
  DESCRIPTION VARCHAR(4000), 
  CONSTRAINT EXPORT_LOCK_CHK CHECK (id = 1),
  CONSTRAINT EXPORT_LOCK_PK PRIMARY KEY (ID)
);

CREATE TABLE UNADDRESSED_ROAD_LINK (
  LINK_ID BIGINT NOT NULL,
  START_ADDR_M INTEGER, 
  END_ADDR_M INTEGER, 
  ROAD_NUMBER INTEGER, 
  ROAD_PART_NUMBER INTEGER, 
  ANOMALY_CODE SMALLINT NOT NULL, 
  START_M NUMERIC(8,3), 
  END_M NUMERIC(8,3), 
  GEOMETRY GEOMETRY
);

CREATE TABLE MUNICIPALITY (
  ID BIGINT NOT NULL,
  NAME_FI VARCHAR(128), 
  NAME_SV VARCHAR(128), 
  ELY_NRO SMALLINT, 
  ROAD_MAINTAINER_ID BIGINT,
  CONSTRAINT MUNICIPALITY_PK PRIMARY KEY (ID), 
  CONSTRAINT MUNI_ELY_MANTAINER_UK UNIQUE (ID, ELY_NRO, ROAD_MAINTAINER_ID)
);

CREATE TABLE PROJECT (
  ID BIGINT NOT NULL,
  STATE SMALLINT DEFAULT 0 NOT NULL, 
  NAME VARCHAR(32) NOT NULL,
  ELY SMALLINT, 
  CREATED_BY VARCHAR(32) NOT NULL, 
  CREATED_DATE DATE DEFAULT current_date NOT NULL, 
  MODIFIED_BY VARCHAR(32), 
  MODIFIED_DATE DATE, 
  ADD_INFO VARCHAR(1000),
  START_DATE DATE,
  STATUS_INFO VARCHAR(1000),
  TR_ID BIGINT,
  COORD_X NUMERIC(10,3), 
  COORD_Y NUMERIC(10,3), 
  ZOOM SMALLINT, 
  CONSTRAINT PROJECT_PK PRIMARY KEY (ID)
);

CREATE TABLE PROJECT_RESERVED_ROAD_PART (
  ID BIGINT NOT NULL,
  ROAD_NUMBER INTEGER NOT NULL, 
  ROAD_PART_NUMBER INTEGER NOT NULL, 
  PROJECT_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(128), 
  CONSTRAINT PROJECT_RESERVED_ROAD_PART_PK PRIMARY KEY (ID), 
  CONSTRAINT RESERVED_ROAD_UK UNIQUE (ROAD_NUMBER, ROAD_PART_NUMBER),
  CONSTRAINT RESERVED_ROAD_PROJECT_UK UNIQUE (PROJECT_ID, ROAD_NUMBER, ROAD_PART_NUMBER),
  CONSTRAINT PRRP_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
);

-- TODO Why we have Project_link_history and not just have here valid_from and valid_to -fields?
-- TODO Geometry column should be of type SDO_GEOMETRY! (Check VIITE-1591)
CREATE TABLE PROJECT_LINK (
  ID BIGINT NOT NULL,
  PROJECT_ID BIGINT NOT NULL,
  TRACK SMALLINT NOT NULL,
  DISCONTINUITY_TYPE SMALLINT DEFAULT 5 NOT NULL, 
  ROAD_NUMBER INTEGER CONSTRAINT ROAD_NOT_NULL NOT NULL, 
  ROAD_PART_NUMBER INTEGER CONSTRAINT PART_NOT_NULL NOT NULL, 
  START_ADDR_M INTEGER, 
  END_ADDR_M INTEGER, 
  CREATED_BY VARCHAR(32) NOT NULL, 
  MODIFIED_BY VARCHAR(32), 
  CREATED_DATE DATE DEFAULT current_date NOT NULL, 
  MODIFIED_DATE DATE, 
  STATUS SMALLINT, 
  CALIBRATION_POINTS SMALLINT DEFAULT 0 NOT NULL,
  ROAD_TYPE SMALLINT DEFAULT 99 NOT NULL,
  ROADWAY_ID BIGINT,
  LINEAR_LOCATION_ID BIGINT,
  CONNECTED_LINK_ID BIGINT,
  ELY SMALLINT, 
  REVERSED SMALLINT DEFAULT 0, 
  GEOMETRY VARCHAR(4000) DEFAULT NULL, 
  SIDE SMALLINT,
  START_MEASURE NUMERIC(8,3), 
  END_MEASURE NUMERIC(8,3), 
  LINK_ID BIGINT,
  ADJUSTED_TIMESTAMP NUMERIC(13,0) DEFAULT 0 NOT NULL, 
  LINK_SOURCE SMALLINT DEFAULT 1, 
  CALIBRATION_POINTS_SOURCE SMALLINT DEFAULT 0, 
  CONSTRAINT PROJECT_LINK_PK PRIMARY KEY (ID),
  CONSTRAINT PROJECT_LINK_ADDRESS_CHK CHECK ((road_number is null and road_part_number is null) or
    (road_number is not null and road_part_number is not null and start_addr_m is not null and end_addr_m is not null)), 
  CONSTRAINT LINK_RESERVED_FK FOREIGN KEY (PROJECT_ID, ROAD_NUMBER, ROAD_PART_NUMBER) REFERENCES PROJECT_RESERVED_ROAD_PART (PROJECT_ID, ROAD_NUMBER, ROAD_PART_NUMBER),
  CONSTRAINT PROJECT_LINK_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE,
  CONSTRAINT PROJECT_LINK_ROADWAY_FK FOREIGN KEY (ROADWAY_ID) REFERENCES ROADWAY (ID),
  CONSTRAINT PROJECT_LINK_LINEAR_LOC_FK FOREIGN KEY (LINEAR_LOCATION_ID) REFERENCES LINEAR_LOCATION (ID)
);

CREATE TABLE PROJECT_CALIBRATION_POINT (
  ID BIGINT NOT NULL,
  PROJECT_LINK_ID BIGINT NOT NULL,
  PROJECT_ID BIGINT NOT NULL,
  LINK_M NUMERIC(8,3) NOT NULL, 
  ADDRESS_M INTEGER NOT NULL, 
  CONSTRAINT PROJECT_CALIBRATION_POINT_PK PRIMARY KEY (ID),
  CONSTRAINT PCALPOINT_PLINK_FK FOREIGN KEY (PROJECT_LINK_ID) REFERENCES PROJECT_LINK (ID) ON DELETE CASCADE,
  CONSTRAINT PCALPOINT_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE
);

-- TODO Why we have Project_link_history and not just have here valid_from and valid_to -fields?
CREATE TABLE PROJECT_LINK_HISTORY (
  ID BIGINT NOT NULL,
  PROJECT_ID BIGINT NOT NULL,
  TRACK SMALLINT NOT NULL,
  DISCONTINUITY_TYPE SMALLINT DEFAULT 5 NOT NULL, 
  ROAD_NUMBER INTEGER, 
  ROAD_PART_NUMBER INTEGER, 
  START_ADDR_M INTEGER, 
  END_ADDR_M INTEGER, 
  CREATED_BY VARCHAR(32) NOT NULL, 
  MODIFIED_BY VARCHAR(32), 
  CREATED_DATE DATE DEFAULT current_date NOT NULL, 
  MODIFIED_DATE DATE, 
  STATUS SMALLINT, 
  CALIBRATION_POINTS SMALLINT DEFAULT 0 NOT NULL, 
  ROAD_TYPE SMALLINT DEFAULT 99 NOT NULL, 
  ROADWAY_ID BIGINT,
  LINEAR_LOCATION_ID BIGINT,
  CONNECTED_LINK_ID BIGINT,
  ELY SMALLINT, 
  REVERSED SMALLINT DEFAULT 0, 
  GEOMETRY VARCHAR(4000) DEFAULT NULL, 
  SIDE INTEGER,
  START_MEASURE NUMERIC(8,3), 
  END_MEASURE NUMERIC(8,3), 
  LINK_ID BIGINT,
  ADJUSTED_TIMESTAMP BIGINT DEFAULT 0 NOT NULL,
  LINK_SOURCE SMALLINT DEFAULT (1), 
  CALIBRATION_POINTS_SOURCE SMALLINT DEFAULT 0, 
  CONSTRAINT PROJECT_LINK_HIST_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PROJECT_LINK_NAME (
  ID BIGINT NOT NULL,
  PROJECT_ID BIGINT,
  ROAD_NUMBER INTEGER, 
  ROAD_NAME VARCHAR(255), 
  CONSTRAINT PROJECT_LINK_NAME_PK PRIMARY KEY (ID), 
  CONSTRAINT PROJECT_LINK_NAME_UK UNIQUE (PROJECT_ID, ROAD_NUMBER),
  CONSTRAINT PROJECT_LINK_NAME_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
);

CREATE TABLE PUBLISHED_ROAD_NETWORK (
  ID BIGINT NOT NULL,
  CREATED TIMESTAMP (6) NOT NULL, 
  VALID_TO TIMESTAMP (6), 
  CONSTRAINT PUBLISHED_ROAD_NETWORK_PK PRIMARY KEY (ID)
);

CREATE TABLE PUBLISHED_ROADWAY (
  NETWORK_ID BIGINT NOT NULL,
  ROADWAY_ID BIGINT NOT NULL,
  CONSTRAINT PUBLISHED_ROADWAY_PK PRIMARY KEY (NETWORK_ID, ROADWAY_ID),
  CONSTRAINT PUBROADADDR_PUBROADNETWORK_FK FOREIGN KEY (NETWORK_ID) REFERENCES PUBLISHED_ROAD_NETWORK (ID),
  CONSTRAINT PUBROADADDR_ROADWAY_FK FOREIGN KEY (ROADWAY_ID) REFERENCES ROADWAY (ID)
);

CREATE TABLE ROAD_NETWORK_ERROR (
  ID BIGINT NOT NULL,
  ROADWAY_ID BIGINT NOT NULL,
  LINEAR_LOCATION_ID BIGINT NOT NULL,
  ERROR_CODE BIGINT NOT NULL,
  ERROR_TIMESTAMP BIGINT DEFAULT 0,
  ROAD_NETWORK_VERSION BIGINT,
  CONSTRAINT ROAD_NETWORK_ERROR_PK PRIMARY KEY (ID),
  CONSTRAINT ADDRESS_ERROR_VERSION_UK UNIQUE (ROADWAY_ID, LINEAR_LOCATION_ID, ERROR_CODE, ROAD_NETWORK_VERSION),
  CONSTRAINT RNE_ROADWAY_FK FOREIGN KEY (ROADWAY_ID) REFERENCES ROADWAY (ID),
  CONSTRAINT RNE_LL_FK FOREIGN KEY (LINEAR_LOCATION_ID) REFERENCES LINEAR_LOCATION (ID),
  CONSTRAINT ROAD_NETWORK_FK FOREIGN KEY (ROAD_NETWORK_VERSION) REFERENCES PUBLISHED_ROAD_NETWORK (ID) ON DELETE CASCADE
);

CREATE TABLE ROADWAY_CHANGES (
  PROJECT_ID BIGINT NOT NULL,
  CHANGE_TYPE SMALLINT NOT NULL,
  OLD_ROAD_NUMBER INTEGER, 
  NEW_ROAD_NUMBER INTEGER, 
  OLD_ROAD_PART_NUMBER INTEGER, 
  NEW_ROAD_PART_NUMBER INTEGER, 
  OLD_TRACK SMALLINT,
  NEW_TRACK SMALLINT,
  OLD_START_ADDR_M INTEGER, 
  NEW_START_ADDR_M INTEGER, 
  OLD_END_ADDR_M INTEGER, 
  NEW_END_ADDR_M INTEGER, 
  NEW_DISCONTINUITY SMALLINT NOT NULL, 
  NEW_ROAD_TYPE SMALLINT NOT NULL, 
  NEW_ELY SMALLINT NOT NULL, 
  OLD_ROAD_TYPE SMALLINT, 
  OLD_DISCONTINUITY SMALLINT, 
  OLD_ELY SMALLINT, 
  REVERSED SMALLINT DEFAULT 0
);

CREATE TABLE ROAD_NAME (
  ID BIGINT NOT NULL,
  ROAD_NUMBER INTEGER NOT NULL, 
  ROAD_NAME VARCHAR(255) NOT NULL, 
  START_DATE DATE NOT NULL, 
  END_DATE DATE, 
  VALID_FROM DATE DEFAULT current_date NOT NULL,
  VALID_TO DATE, 
  CREATED_BY VARCHAR(32) NOT NULL, 
  CREATED_TIME TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
  CONSTRAINT ROAD_NAME_PK PRIMARY KEY (ID)
);

CREATE TABLE SERVICE_USER (
  ID BIGINT NOT NULL,
  USERNAME VARCHAR(256) NOT NULL, 
  CONFIGURATION VARCHAR(4000), 
  CONSTRAINT SERVICE_USER_UK UNIQUE (USERNAME),
  CONSTRAINT SERVICE_USER_PK PRIMARY KEY (ID)
);

CREATE GLOBAL TEMPORARY TABLE TEMP_ID (
  ID BIGINT NOT NULL,
  CONSTRAINT TEMP_ID_PK PRIMARY KEY (ID)
) ON COMMIT DELETE ROWS;
