--------------------------------------------------------
--  Table ADMINISTRATIVE_CLASS
--------------------------------------------------------

CREATE TABLE "ADMINISTRATIVE_CLASS" 
(
  "ID" NUMBER,
	"MML_ID" NUMBER(10,0), 
	"LINK_ID" NUMBER(38,0), 
	"ADMINISTRATIVE_CLASS" NUMBER(10,0), 
	"VVH_ADMINISTRATIVE_CLASS" NUMBER(10,0), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(128 BYTE), 
	"CREATED_BY" VARCHAR2(128 BYTE), 
	"VALID_TO" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table CALIBRATION_POINT
--------------------------------------------------------

CREATE TABLE "CALIBRATION_POINT"
(
  "ID" NUMBER,
	"PROJECT_LINK_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"LINK_M" NUMBER(8,3), 
	"ADDRESS_M" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table EXPORT_LOCK
--------------------------------------------------------

CREATE TABLE "EXPORT_LOCK"
(
  "ID" NUMBER(*,0),
	"DESCRIPTION" VARCHAR2(4000 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table FUNCTIONAL_CLASS
--------------------------------------------------------

CREATE TABLE "FUNCTIONAL_CLASS"
(
  "MML_ID" NUMBER(10,0),
	"FUNCTIONAL_CLASS" NUMBER(9,0), 
	"MODIFIED_DATE" TIMESTAMP (6) DEFAULT current_timestamp, 
	"MODIFIED_BY" VARCHAR2(128 BYTE), 
	"LINK_ID" NUMBER(38,0), 
	"ID" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table INCOMPLETE_LINK
--------------------------------------------------------

CREATE TABLE "INCOMPLETE_LINK"
(
  "MML_ID" NUMBER,
	"MUNICIPALITY_CODE" NUMBER, 
	"ADMINISTRATIVE_CLASS" NUMBER(10,0), 
	"LINK_ID" NUMBER(38,0), 
	"ID" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table LINK_TYPE
--------------------------------------------------------

CREATE TABLE "LINK_TYPE"
(
  "MML_ID" NUMBER(10,0),
	"LINK_TYPE" NUMBER(9,0), 
	"MODIFIED_DATE" TIMESTAMP (6) DEFAULT current_timestamp, 
	"MODIFIED_BY" VARCHAR2(128 BYTE), 
	"LINK_ID" NUMBER(38,0), 
	"ID" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table LRM_POSITION
--------------------------------------------------------

CREATE TABLE "LRM_POSITION"
(
  "ID" NUMBER(38,0),
	"LANE_CODE" NUMBER(5,0), 
	"SIDE_CODE" NUMBER(5,0), 
	"START_MEASURE" NUMBER(8,3), 
	"END_MEASURE" NUMBER(8,3), 
	"MML_ID" NUMBER(10,0), 
	"LINK_ID" NUMBER(38,0), 
	"ADJUSTED_TIMESTAMP" NUMBER(38,0) DEFAULT 0, 
	"MODIFIED_DATE" TIMESTAMP (6) DEFAULT current_timestamp, 
	"LINK_SOURCE" NUMBER(*,0) DEFAULT (1)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table MISSING_ROAD_ADDRESS
--------------------------------------------------------

CREATE TABLE "MISSING_ROAD_ADDRESS"
(
  "LINK_ID" NUMBER(38,0),
	"START_ADDR_M" NUMBER, 
	"END_ADDR_M" NUMBER, 
	"ROAD_NUMBER" NUMBER, 
	"ROAD_PART_NUMBER" NUMBER, 
	"ANOMALY_CODE" NUMBER(2,0), 
	"START_M" NUMBER, 
	"END_M" NUMBER, 
	"GEOMETRY" "SDO_GEOMETRY"
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUNICIPALITY
--------------------------------------------------------

CREATE TABLE "MUNICIPALITY"
(
  "ID" NUMBER,
	"NAME_FI" VARCHAR2(128 BYTE),
	"NAME_SV" VARCHAR2(128 BYTE),
	"ELY_NRO" NUMBER,
	"ROAD_MAINTAINER_ID" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table PROJECT
--------------------------------------------------------

CREATE TABLE "PROJECT"
(
  "ID" NUMBER,
	"STATE" NUMBER DEFAULT 0, 
	"NAME" VARCHAR2(32 BYTE), 
	"ELY" NUMBER, 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MODIFIED_BY" VARCHAR2(32 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ADD_INFO" VARCHAR2(1000 BYTE), 
	"START_DATE" DATE, 
	"STATUS_INFO" VARCHAR2(1000 BYTE), 
	"CHECK_COUNTER" NUMBER DEFAULT 0, 
	"TR_ID" NUMBER, 
	"COORD_X" NUMBER(10,3), 
	"COORD_Y" NUMBER(10,3), 
	"ZOOM" NUMBER(2,0)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table PROJECT_LINK
--------------------------------------------------------

CREATE TABLE "PROJECT_LINK"
(
  "ID" NUMBER,
	"PROJECT_ID" NUMBER, 
	"TRACK_CODE" NUMBER, 
	"DISCONTINUITY_TYPE" NUMBER DEFAULT 5, 
	"ROAD_NUMBER" NUMBER, 
	"ROAD_PART_NUMBER" NUMBER, 
	"START_ADDR_M" NUMBER, 
	"END_ADDR_M" NUMBER, 
	"LRM_POSITION_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"MODIFIED_BY" VARCHAR2(32 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER, 
	"CALIBRATION_POINTS" NUMBER DEFAULT 0, 
	"ROAD_TYPE" NUMBER DEFAULT 99, 
	"ROAD_ADDRESS_ID" NUMBER, 
	"CONNECTED_LINK_ID" NUMBER, 
	"ELY" NUMBER, 
	"REVERSED" NUMBER(1,0) DEFAULT 0, 
	"GEOMETRY" VARCHAR2(4000 BYTE) DEFAULT NULL
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table PROJECT_LINK_HISTORY
--------------------------------------------------------

CREATE TABLE "PROJECT_LINK_HISTORY"
(
  "ID" NUMBER,
	"PROJECT_ID" NUMBER, 
	"TRACK_CODE" NUMBER, 
	"DISCONTINUITY_TYPE" NUMBER DEFAULT 5, 
	"ROAD_NUMBER" NUMBER, 
	"ROAD_PART_NUMBER" NUMBER, 
	"START_ADDR_M" NUMBER, 
	"END_ADDR_M" NUMBER, 
	"LRM_POSITION_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"MODIFIED_BY" VARCHAR2(32 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER, 
	"CALIBRATION_POINTS" NUMBER DEFAULT 0, 
	"ROAD_TYPE" NUMBER DEFAULT 99
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table PROJECT_RESERVED_ROAD_PART
--------------------------------------------------------

CREATE TABLE "PROJECT_RESERVED_ROAD_PART"
(
  "ID" NUMBER,
	"ROAD_NUMBER" NUMBER, 
	"ROAD_PART_NUMBER" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(128 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table PUBLISHED_ROAD_ADDRESS
--------------------------------------------------------

CREATE TABLE "PUBLISHED_ROAD_ADDRESS"
(
  "NETWORK_ID" NUMBER(*,0),
	"ROAD_ADDRESS_ID" NUMBER(*,0)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table PUBLISHED_ROAD_NETWORK
--------------------------------------------------------

CREATE TABLE "PUBLISHED_ROAD_NETWORK"
(
  "ID" NUMBER(*,0),
	"CREATED" TIMESTAMP (6), 
	"VALID_TO" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table ROAD_ADDRESS
--------------------------------------------------------

CREATE TABLE "ROAD_ADDRESS"
(
  "ID" NUMBER,
	"ROAD_NUMBER" NUMBER, 
	"ROAD_PART_NUMBER" NUMBER, 
	"TRACK_CODE" NUMBER, 
	"DISCONTINUITY" NUMBER, 
	"START_ADDR_M" NUMBER, 
	"END_ADDR_M" NUMBER, 
	"LRM_POSITION_ID" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"VALID_FROM" DATE DEFAULT sysdate, 
	"CALIBRATION_POINTS" NUMBER DEFAULT 0, 
	"FLOATING" CHAR(1 BYTE) DEFAULT '0', 
	"GEOMETRY" "SDO_GEOMETRY", 
	"VALID_TO" DATE, 
	"ELY" NUMBER, 
	"ROAD_TYPE" NUMBER, 
	"TERMINATED" NUMBER DEFAULT 0, 
	"COMMON_HISTORY_ID" NUMBER(38,0)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table ROAD_ADDRESS_CHANGES
--------------------------------------------------------

CREATE TABLE "ROAD_ADDRESS_CHANGES"
(
  "PROJECT_ID" NUMBER,
	"CHANGE_TYPE" NUMBER, 
	"OLD_ROAD_NUMBER" NUMBER, 
	"NEW_ROAD_NUMBER" NUMBER, 
	"OLD_ROAD_PART_NUMBER" NUMBER, 
	"NEW_ROAD_PART_NUMBER" NUMBER, 
	"OLD_TRACK_CODE" NUMBER, 
	"NEW_TRACK_CODE" NUMBER, 
	"OLD_START_ADDR_M" NUMBER, 
	"NEW_START_ADDR_M" NUMBER, 
	"OLD_END_ADDR_M" NUMBER, 
	"NEW_END_ADDR_M" NUMBER, 
	"NEW_DISCONTINUITY" NUMBER, 
	"NEW_ROAD_TYPE" NUMBER, 
	"NEW_ELY" NUMBER, 
	"OLD_ROAD_TYPE" NUMBER, 
	"OLD_DISCONTINUITY" NUMBER, 
	"OLD_ELY" NUMBER, 
	"REVERSED" NUMBER(1,0) DEFAULT 0
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table ROAD_NAMES
--------------------------------------------------------

CREATE TABLE "ROAD_NAMES"
(
  "ID" NUMBER,
	"ROAD_NUMBER" NUMBER, 
	"ROAD_NAME" VARCHAR2(255 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table ROAD_NETWORK_ERRORS
--------------------------------------------------------

CREATE TABLE "ROAD_NETWORK_ERRORS"
(
  "ID" NUMBER(*,0),
	"ROAD_ADDRESS_ID" NUMBER(*,0), 
	"ERROR_CODE" NUMBER
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table SERVICE_USER
--------------------------------------------------------

CREATE TABLE "SERVICE_USER"
(
  "ID" NUMBER,
	"USERNAME" VARCHAR2(256 BYTE), 
	"CONFIGURATION" VARCHAR2(4000 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Table TEMP_ID
--------------------------------------------------------

CREATE GLOBAL TEMPORARY TABLE "TEMP_ID"
(
  "ID" NUMBER
) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  Table TRAFFIC_DIRECTION
--------------------------------------------------------

CREATE TABLE "TRAFFIC_DIRECTION"
(
  "MML_ID" NUMBER(10,0),
	"TRAFFIC_DIRECTION" NUMBER(9,0), 
	"MODIFIED_DATE" TIMESTAMP (6) DEFAULT current_timestamp, 
	"MODIFIED_BY" VARCHAR2(128 BYTE), 
	"LINK_ID" NUMBER(38,0), 
	"ID" NUMBER
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;