ALTER TABLE NODE_POINT ADD (NODE_NUMBER NUMBER);
UPDATE NODE_POINT NP SET NP.NODE_NUMBER = (SELECT NODE.NODE_NUMBER FROM NODE NODE WHERE NODE.ID = NP.NODE_ID);
ALTER TABLE NODE_POINT DROP COLUMN NODE_ID;

ALTER TABLE JUNCTION ADD (NODE_NUMBER NUMBER);
UPDATE JUNCTION J SET J.NODE_NUMBER = (SELECT NODE.NODE_NUMBER FROM NODE NODE WHERE NODE.ID = J.NODE_ID);
ALTER TABLE JUNCTION DROP COLUMN NODE_ID;

ALTER TABLE NODE_POINT DROP COLUMN START_DATE;
ALTER TABLE NODE_POINT DROP COLUMN END_DATE;
ALTER TABLE JUNCTION_POINT DROP COLUMN START_DATE;
ALTER TABLE JUNCTION_POINT DROP COLUMN END_DATE;

ALTER TABLE NODE_POINT ADD ("TYPE" NUMBER DEFAULT 99 NOT NULL);