  CREATE TABLE COMPLEMENTARY_FILTER
   (	LINK_ID BIGINT NOT NULL,
	 CONSTRAINT COMPLEMENTARY_FILTER_PK PRIMARY KEY (LINK_ID)
   );

  CREATE TABLE EXPORT_LOCK
   (	ID SMALLINT NOT NULL,
	DESCRIPTION VARCHAR(4000),
	 CONSTRAINT EXPORT_LOCK_CHK CHECK (id = 1),
	 CONSTRAINT EXPORT_LOCK_PK PRIMARY KEY (ID)
   );

  CREATE TABLE JUNCTION
   (	ID BIGINT NOT NULL,
	JUNCTION_NUMBER SMALLINT,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_TO TIMESTAMP,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	NODE_NUMBER BIGINT,
	 CONSTRAINT JUNCTION_PK PRIMARY KEY (ID)
   );

  CREATE TABLE LINK
   (	ID BIGINT NOT NULL,
	SOURCE SMALLINT DEFAULT 1 NOT NULL,
	ADJUSTED_TIMESTAMP NUMERIC(13,0) DEFAULT 0 NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT LINK_PK PRIMARY KEY (ID)
   );

  CREATE TABLE MUNICIPALITY
   (	ID BIGINT NOT NULL,
	NAME_FI VARCHAR(128),
	NAME_SV VARCHAR(128),
	ELY_NRO SMALLINT,
	ROAD_MAINTAINER_ID BIGINT,
	 CONSTRAINT MUNICIPALITY_PK PRIMARY KEY (ID),
	 CONSTRAINT MUNI_ELY_MANTAINER_UK UNIQUE (ID, ELY_NRO, ROAD_MAINTAINER_ID)
   );

  CREATE TABLE NODE
   (	ID BIGINT NOT NULL,
	NODE_NUMBER BIGINT NOT NULL,
	COORDINATES GEOMETRY NOT NULL,
	NAME VARCHAR(30),
	TYPE SMALLINT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	VALID_TO TIMESTAMP,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	PUBLISHED_TIME TIMESTAMP,
	EDITOR VARCHAR(32),
	REGISTRATION_DATE TIMESTAMP DEFAULT TO_DATE('1900', 'yyyy') NOT NULL,
	 CONSTRAINT NODE_PK PRIMARY KEY (ID)
   );

  CREATE TABLE PROJECT
   (	ID BIGINT NOT NULL,
	STATE SMALLINT DEFAULT 0 NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_DATE TIMESTAMP DEFAULT current_timestamp NOT NULL,
	MODIFIED_BY VARCHAR(32),
	MODIFIED_DATE TIMESTAMP,
	ADD_INFO VARCHAR(1000),
	START_DATE DATE,
	STATUS_INFO VARCHAR(1000),
	TR_ID BIGINT,
	COORD_X NUMERIC(10,3),
	COORD_Y NUMERIC(10,3),
	ZOOM SMALLINT,
	 CONSTRAINT PROJECT_PK PRIMARY KEY (ID)
   );

  CREATE TABLE PUBLISHED_ROAD_NETWORK
   (	ID BIGINT NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	VALID_TO TIMESTAMP,
	 CONSTRAINT PUBLISHED_ROAD_NETWORK_PK PRIMARY KEY (ID)
   );

  CREATE TABLE ROADWAY
   (	ID BIGINT NOT NULL,
	ROADWAY_NUMBER BIGINT NOT NULL,
	ROAD_NUMBER INTEGER NOT NULL,
	ROAD_PART_NUMBER INTEGER NOT NULL,
	TRACK SMALLINT NOT NULL,
	START_ADDR_M INTEGER NOT NULL,
	END_ADDR_M INTEGER NOT NULL,
	REVERSED SMALLINT NOT NULL,
	DISCONTINUITY SMALLINT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	ROAD_TYPE SMALLINT NOT NULL,
	ELY SMALLINT,
	TERMINATED SMALLINT DEFAULT 0 NOT NULL,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_TO TIMESTAMP,
	 CONSTRAINT TERMINATION_END_DATE_CHK CHECK (TERMINATED = 0 OR (TERMINATED in (1,2) AND END_DATE IS NOT NULL)),
	 CONSTRAINT ROADWAY_PK PRIMARY KEY (ID),
	 CONSTRAINT ROADWAY_HISTORY_UK UNIQUE (ROAD_NUMBER, ROAD_PART_NUMBER, START_ADDR_M, END_ADDR_M, TRACK, DISCONTINUITY, START_DATE, END_DATE, VALID_FROM, VALID_TO, ELY, ROAD_TYPE, TERMINATED)
   );

  CREATE TABLE ROADWAY_CHANGES
   (	PROJECT_ID BIGINT NOT NULL,
	CHANGE_TYPE SMALLINT NOT NULL,
	OLD_ROAD_NUMBER INTEGER,
	NEW_ROAD_NUMBER INTEGER,
	OLD_ROAD_PART_NUMBER INTEGER,
	NEW_ROAD_PART_NUMBER INTEGER,
	OLD_TRACK SMALLINT,
	NEW_TRACK SMALLINT,
	OLD_START_ADDR_M INTEGER,
	NEW_START_ADDR_M INTEGER,
	OLD_END_ADDR_M INTEGER,
	NEW_END_ADDR_M INTEGER,
	NEW_DISCONTINUITY SMALLINT NOT NULL,
	NEW_ROAD_TYPE SMALLINT NOT NULL,
	NEW_ELY SMALLINT NOT NULL,
	OLD_ROAD_TYPE SMALLINT,
	OLD_DISCONTINUITY SMALLINT,
	OLD_ELY SMALLINT,
	REVERSED SMALLINT DEFAULT 0,
	ROADWAY_CHANGE_ID BIGINT NOT NULL
   );

  CREATE TABLE ROADWAY_POINT
   (	ID BIGINT NOT NULL,
	ROADWAY_NUMBER BIGINT NOT NULL,
	ADDR_M INTEGER NOT NULL,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	MODIFIED_BY VARCHAR(32) NOT NULL,
	MODIFIED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT ROADWAY_POINT_PK PRIMARY KEY (ID),
	 CONSTRAINT ROADWAY_POINT_UK1 UNIQUE (ROADWAY_NUMBER, ADDR_M) DEFERRABLE INITIALLY DEFERRED
   );

  CREATE TABLE ROAD_NAME
   (	ID BIGINT NOT NULL,
	ROAD_NUMBER INTEGER NOT NULL,
	ROAD_NAME VARCHAR(50) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_TO TIMESTAMP,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	 CONSTRAINT ROAD_NAME_PK PRIMARY KEY (ID)
   );

  CREATE TABLE SERVICE_USER
   (	ID BIGINT NOT NULL,
	USERNAME VARCHAR(256) NOT NULL,
	CONFIGURATION VARCHAR(4000),
	 CONSTRAINT SERVICE_USER_PK PRIMARY KEY (ID),
	 CONSTRAINT SERVICE_USER_UK UNIQUE (USERNAME)
   );

  CREATE GLOBAL TEMPORARY TABLE TEMP_ID
   (	ID BIGINT NOT NULL,
	 CONSTRAINT TEMP_ID_PK PRIMARY KEY (ID)
   ) ON COMMIT DELETE ROWS ;

  CREATE TABLE UNADDRESSED_ROAD_LINK
   (	LINK_ID BIGINT NOT NULL,
	START_ADDR_M INTEGER,
	END_ADDR_M INTEGER,
	ROAD_NUMBER INTEGER,
	ROAD_PART_NUMBER INTEGER,
	ANOMALY_CODE SMALLINT NOT NULL,
	START_M NUMERIC(8,3),
	END_M NUMERIC(8,3),
	GEOMETRY GEOMETRY
   );

  CREATE TABLE CALIBRATION_POINT
   (	ID BIGINT NOT NULL,
	ROADWAY_POINT_ID BIGINT NOT NULL,
	LINK_ID BIGINT NOT NULL,
	START_END SMALLINT DEFAULT 0 NOT NULL,
	TYPE SMALLINT DEFAULT 0 NOT NULL,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_TO TIMESTAMP,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT CP_START_END_CHK CHECK (START_END in (0,1)),
	 CONSTRAINT CALIBRATION_POINT_PK PRIMARY KEY (ID),
	 CONSTRAINT CP_TYPE_CHK CHECK (TYPE in (1, 2, 3)),
	 CONSTRAINT CP_ROADWAY_POINT_FK FOREIGN KEY (ROADWAY_POINT_ID)
	  REFERENCES ROADWAY_POINT (ID),
	 CONSTRAINT CP_LINK_FK FOREIGN KEY (LINK_ID)
	  REFERENCES LINK (ID)
   );

  CREATE TABLE JUNCTION_POINT
   (	ID BIGINT NOT NULL,
	BEFORE_AFTER SMALLINT NOT NULL,
	ROADWAY_POINT_ID BIGINT NOT NULL,
	JUNCTION_ID BIGINT NOT NULL,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_TO TIMESTAMP,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT JUNCTION_POINT_CHK1 CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))),
	 CONSTRAINT JUNCTION_POINT_PK PRIMARY KEY (ID),
	 CONSTRAINT JUNCTION_POINT_FK1 FOREIGN KEY (JUNCTION_ID)
	  REFERENCES JUNCTION (ID),
	 CONSTRAINT FK_JP_ROADWAY_POINT_ID FOREIGN KEY (ROADWAY_POINT_ID)
	  REFERENCES ROADWAY_POINT (ID)
   );

  CREATE TABLE LINEAR_LOCATION
   (	ID BIGINT NOT NULL,
	ROADWAY_NUMBER BIGINT NOT NULL,
	ORDER_NUMBER INTEGER DEFAULT 0 NOT NULL,
	LINK_ID BIGINT,
	START_MEASURE NUMERIC(8,3),
	END_MEASURE NUMERIC(8,3),
	SIDE SMALLINT,
	GEOMETRY GEOMETRY,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_TO TIMESTAMP,
	CREATED_BY VARCHAR(128),
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	 CONSTRAINT LINEAR_LOCATION_PK PRIMARY KEY (ID),
	 CONSTRAINT LINEAR_LOCATION_UK UNIQUE (ROADWAY_NUMBER, ORDER_NUMBER, LINK_ID, START_MEASURE, END_MEASURE, VALID_TO, SIDE),
	 CONSTRAINT LINEAR_LOCATION_LINK_FK FOREIGN KEY (LINK_ID)
	  REFERENCES LINK (ID)
   );

  CREATE TABLE NODE_POINT
   (	ID BIGINT NOT NULL,
	BEFORE_AFTER SMALLINT NOT NULL,
	ROADWAY_POINT_ID BIGINT NOT NULL,
	VALID_FROM TIMESTAMP DEFAULT current_timestamp NOT NULL,
	VALID_TO TIMESTAMP,
	CREATED_BY VARCHAR(32) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT current_timestamp NOT NULL,
	NODE_NUMBER BIGINT,
	TYPE SMALLINT DEFAULT 99 NOT NULL,
	 CONSTRAINT NODE_POINT_CHK1 CHECK (BEFORE_AFTER IS NULL OR (BEFORE_AFTER in (1,2))),
	 CONSTRAINT NODE_POINT_PK PRIMARY KEY (ID),
	 CONSTRAINT FK_NP_ROADWAY_POINT_ID FOREIGN KEY (ROADWAY_POINT_ID)
	  REFERENCES ROADWAY_POINT (ID)
   );

  CREATE TABLE PROJECT_LINK_HISTORY
   (	ID BIGINT NOT NULL,
	PROJECT_ID BIGINT NOT NULL,
	TRACK SMALLINT NOT NULL,
	DISCONTINUITY_TYPE SMALLINT DEFAULT 5 NOT NULL,
	ROAD_NUMBER INTEGER,
	ROAD_PART_NUMBER INTEGER,
	START_ADDR_M INTEGER,
	END_ADDR_M INTEGER,
	CREATED_BY VARCHAR(32) NOT NULL,
	MODIFIED_BY VARCHAR(32),
	CREATED_DATE TIMESTAMP DEFAULT current_timestamp NOT NULL,
	MODIFIED_DATE TIMESTAMP,
	STATUS SMALLINT,
	ROAD_TYPE SMALLINT DEFAULT 99 NOT NULL,
	ROADWAY_ID BIGINT,
	LINEAR_LOCATION_ID BIGINT,
	CONNECTED_LINK_ID BIGINT,
	ELY SMALLINT,
	REVERSED SMALLINT DEFAULT 0,
	SIDE INTEGER,
	START_MEASURE NUMERIC(8,3),
	END_MEASURE NUMERIC(8,3),
	LINK_ID BIGINT,
	ADJUSTED_TIMESTAMP BIGINT DEFAULT 0 NOT NULL,
	LINK_SOURCE SMALLINT DEFAULT (1),
	GEOMETRY GEOMETRY,
	ORIGINAL_START_ADDR_M INTEGER NOT NULL,
	ORIGINAL_END_ADDR_M INTEGER NOT NULL,
	ROADWAY_NUMBER BIGINT,
	START_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	END_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	ORIG_START_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	ORIG_END_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	 CONSTRAINT PROJECT_LINK_HIST_PROJECT_FK FOREIGN KEY (PROJECT_ID)
	  REFERENCES PROJECT (ID) ON DELETE CASCADE
   );

  CREATE TABLE PROJECT_LINK_NAME
   (	ID BIGINT NOT NULL,
	PROJECT_ID BIGINT,
	ROAD_NUMBER INTEGER,
	ROAD_NAME VARCHAR(255),
	 CONSTRAINT PROJECT_LINK_NAME_PK PRIMARY KEY (ID),
	 CONSTRAINT PROJECT_LINK_NAME_UK UNIQUE (PROJECT_ID, ROAD_NUMBER),
	 CONSTRAINT PROJECT_LINK_NAME_PROJECT_FK FOREIGN KEY (PROJECT_ID)
	  REFERENCES PROJECT (ID)
   );

  CREATE TABLE PROJECT_RESERVED_ROAD_PART
   (	ID BIGINT NOT NULL,
	ROAD_NUMBER INTEGER NOT NULL,
	ROAD_PART_NUMBER INTEGER NOT NULL,
	PROJECT_ID BIGINT NOT NULL,
	CREATED_BY VARCHAR(128),
	 CONSTRAINT PROJECT_RESERVED_ROAD_PART_PK PRIMARY KEY (ID),
	 CONSTRAINT RESERVED_ROAD_PROJECT_UK UNIQUE (PROJECT_ID, ROAD_NUMBER, ROAD_PART_NUMBER),
	 CONSTRAINT PRRP_PROJECT_FK FOREIGN KEY (PROJECT_ID)
	  REFERENCES PROJECT (ID)
   );

  CREATE TABLE PUBLISHED_ROADWAY
   (	NETWORK_ID BIGINT NOT NULL,
	ROADWAY_ID BIGINT NOT NULL,
	 CONSTRAINT PUBLISHED_ROADWAY_PK PRIMARY KEY (NETWORK_ID, ROADWAY_ID),
	 CONSTRAINT PUBROADADDR_PUBROADNETWORK_FK FOREIGN KEY (NETWORK_ID)
	  REFERENCES PUBLISHED_ROAD_NETWORK (ID),
	 CONSTRAINT PUBROADADDR_ROADWAY_FK FOREIGN KEY (ROADWAY_ID)
	  REFERENCES ROADWAY (ID)
   );

  CREATE TABLE ROAD_NETWORK_ERROR
   (	ID BIGINT NOT NULL,
	ROADWAY_ID BIGINT NOT NULL,
	LINEAR_LOCATION_ID BIGINT NOT NULL,
	ERROR_CODE BIGINT NOT NULL,
	ERROR_TIMESTAMP BIGINT DEFAULT 0,
	ROAD_NETWORK_VERSION BIGINT,
	 CONSTRAINT ROAD_NETWORK_ERROR_PK PRIMARY KEY (ID),
	 CONSTRAINT ADDRESS_ERROR_VERSION_UK UNIQUE (ROADWAY_ID, LINEAR_LOCATION_ID, ERROR_CODE, ROAD_NETWORK_VERSION),
	 CONSTRAINT RNE_ROADWAY_FK FOREIGN KEY (ROADWAY_ID)
	  REFERENCES ROADWAY (ID),
	 CONSTRAINT ROAD_NETWORK_FK FOREIGN KEY (ROAD_NETWORK_VERSION)
	  REFERENCES PUBLISHED_ROAD_NETWORK (ID) ON DELETE CASCADE
   );

  CREATE TABLE PROJECT_LINK
   (	ID BIGINT NOT NULL,
	PROJECT_ID BIGINT NOT NULL,
	TRACK SMALLINT NOT NULL,
	DISCONTINUITY_TYPE SMALLINT DEFAULT 5 NOT NULL,
	ROAD_NUMBER INTEGER CONSTRAINT ROAD_NOT_NULL NOT NULL,
	ROAD_PART_NUMBER INTEGER CONSTRAINT PART_NOT_NULL NOT NULL,
	START_ADDR_M INTEGER,
	END_ADDR_M INTEGER,
	CREATED_BY VARCHAR(32) NOT NULL,
	MODIFIED_BY VARCHAR(32),
	CREATED_DATE TIMESTAMP DEFAULT current_timestamp NOT NULL,
	MODIFIED_DATE TIMESTAMP,
	STATUS SMALLINT,
	ROAD_TYPE SMALLINT DEFAULT 99 NOT NULL,
	ROADWAY_ID BIGINT,
	LINEAR_LOCATION_ID BIGINT,
	CONNECTED_LINK_ID BIGINT,
	ELY SMALLINT,
	REVERSED SMALLINT DEFAULT 0,
	SIDE SMALLINT,
	START_MEASURE NUMERIC(8,3),
	END_MEASURE NUMERIC(8,3),
	LINK_ID BIGINT,
	ADJUSTED_TIMESTAMP NUMERIC(13,0) DEFAULT 0 NOT NULL,
	LINK_SOURCE SMALLINT DEFAULT 1,
	GEOMETRY GEOMETRY,
	ORIGINAL_START_ADDR_M INTEGER NOT NULL,
	ORIGINAL_END_ADDR_M INTEGER NOT NULL,
	ROADWAY_NUMBER BIGINT,
	START_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	END_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	ORIG_START_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	ORIG_END_CALIBRATION_POINT SMALLINT DEFAULT 0 NOT NULL,
	 CONSTRAINT PROJECT_LINK_ADDRESS_CHK CHECK ((road_number is null and road_part_number is null) or
    (road_number is not null and road_part_number is not null and start_addr_m is not null and end_addr_m is not null)),
	 CONSTRAINT PROJECT_LINK_PK PRIMARY KEY (ID),
	 CONSTRAINT LINK_RESERVED_FK FOREIGN KEY (PROJECT_ID, ROAD_NUMBER, ROAD_PART_NUMBER)
	  REFERENCES PROJECT_RESERVED_ROAD_PART (PROJECT_ID, ROAD_NUMBER, ROAD_PART_NUMBER),
	 CONSTRAINT PROJECT_LINK_PROJECT_FK FOREIGN KEY (PROJECT_ID)
	  REFERENCES PROJECT (ID) ON DELETE CASCADE,
	 CONSTRAINT PROJECT_LINK_ROADWAY_FK FOREIGN KEY (ROADWAY_ID)
	  REFERENCES ROADWAY (ID),
	 CONSTRAINT PROJECT_LINK_LINEAR_LOC_FK FOREIGN KEY (LINEAR_LOCATION_ID)
	  REFERENCES LINEAR_LOCATION (ID)
   );

  CREATE TABLE ROADWAY_CHANGES_LINK
   (	ROADWAY_CHANGE_ID BIGINT NOT NULL,
	PROJECT_ID BIGINT NOT NULL,
	PROJECT_LINK_ID BIGINT NOT NULL,
	 CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID)
	  REFERENCES PROJECT (ID),
	 CONSTRAINT PROJECT_LINK_FK FOREIGN KEY (PROJECT_LINK_ID)
	  REFERENCES PROJECT_LINK (ID)
   );

  CREATE TABLE PROJECT_CALIBRATION_POINT
   (	ID BIGINT NOT NULL,
	PROJECT_LINK_ID BIGINT NOT NULL,
	PROJECT_ID BIGINT NOT NULL,
	LINK_M NUMERIC(8,3) NOT NULL,
	ADDRESS_M INTEGER NOT NULL,
	 CONSTRAINT PROJECT_CALIBRATION_POINT_PK PRIMARY KEY (ID),
	 CONSTRAINT PCALPOINT_PLINK_FK FOREIGN KEY (PROJECT_LINK_ID)
	  REFERENCES PROJECT_LINK (ID) ON DELETE CASCADE,
	 CONSTRAINT PCALPOINT_PROJECT_FK FOREIGN KEY (PROJECT_ID)
	  REFERENCES PROJECT (ID) ON DELETE CASCADE
   );

