INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
  VALUES ('UNADDRESSED_ROAD_LINK', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',50100,762000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Y',6582000,7800000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Z',0,2000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('M',0,100000,0.1)),
                                    3067);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
  VALUES ('LINEAR_LOCATION', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',50100,762000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Y',6582000,7800000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Z',0,2000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('M',0,100000,0.1)),
                                    3067);

CREATE UNIQUE INDEX PROJECT_CALIBRATION_POINT_I ON PROJECT_CALIBRATION_POINT (ID, PROJECT_LINK_ID, PROJECT_ID);

CREATE INDEX UNADDRESSED_ROAD_LINK_I ON UNADDRESSED_ROAD_LINK (ROAD_NUMBER, ROAD_PART_NUMBER, START_ADDR_M);

CREATE INDEX UNADDRESSED_ROAD_LINK_LINKID_I ON UNADDRESSED_ROAD_LINK (LINK_ID);

CREATE INDEX UNADDRESSED_ROAD_LINK_GEOM_I ON UNADDRESSED_ROAD_LINK (GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX PROJECT_LINK_ROADWAY_I ON PROJECT_LINK (ROADWAY_ID);

CREATE INDEX PROJECT_LINK_CONNECT_I ON PROJECT_LINK (CONNECTED_LINK_ID);

CREATE INDEX PROJECT_LINK_HIST_PRJ_I ON PROJECT_LINK_HISTORY (PROJECT_ID);

CREATE INDEX PROJECT_LINK_HIST_ROAD_I ON PROJECT_LINK_HISTORY (ROAD_NUMBER, ROAD_PART_NUMBER);

CREATE INDEX PROJECT_LINK_PRJ_I ON PROJECT_LINK (PROJECT_ID);

CREATE INDEX PROJECT_LINK_ROAD_I ON PROJECT_LINK (ROAD_NUMBER, ROAD_PART_NUMBER);

CREATE INDEX PROJECT_STATE_I ON PROJECT (STATE);

CREATE INDEX ROADWAY_ADDR_I ON ROADWAY (ROAD_NUMBER, ROAD_PART_NUMBER, TRACK_CODE);

CREATE INDEX ROADWAY_CURRENT_I ON ROADWAY (VALID_TO, END_DATE, TERMINATED);

CREATE INDEX LINEAR_LOCATION_FLOATING_I ON LINEAR_LOCATION (FLOATING);

CREATE INDEX LINEAR_LOCATION_GEOMETRY_I ON LINEAR_LOCATION (GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX LINEAR_LOCATION_LINK_ID_I ON LINEAR_LOCATION (LINK_ID);

CREATE INDEX ROAD_NAME_CURRENT_I ON ROAD_NAME (VALID_TO, END_DATE, ROAD_NUMBER);
