INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
  VALUES ('MISSING_ROAD_ADDRESS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',50100,762000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Y',6582000,7800000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Z',0,2000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('M',0,100000,0.1)),
                                    3067);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
  VALUES ('ROAD_ADDRESS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',50100,762000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Y',6582000,7800000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('Z',0,2000,0.1),
                                      MDSYS.SDO_DIM_ELEMENT('M',0,100000,0.1)),
                                    3067);

--------------------------------
--  Index ROAD_ADDRESS_FLOATING_IDX
--------------------------------------------------------

CREATE INDEX "ROAD_ADDRESS_FLOATING_IDX" ON "ROAD_ADDRESS" ("FLOATING")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index M_ROAD_ADDRESS_GEOMETRY_SX
--------------------------------------------------------

CREATE INDEX "M_ROAD_ADDRESS_GEOMETRY_SX" ON "MISSING_ROAD_ADDRESS" ("GEOMETRY")
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
--------------------------------------------------------
--  Index ROAD_ADDRESS_GEOMETRY_SX
--------------------------------------------------------

CREATE INDEX "ROAD_ADDRESS_GEOMETRY_SX" ON "ROAD_ADDRESS" ("GEOMETRY")
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
--------------------------------------------------------
--  Index MUNI_ELY_MANTAINER_UNIQUE
--------------------------------------------------------

CREATE UNIQUE INDEX "MUNI_ELY_MANTAINER_UNIQUE" ON "MUNICIPALITY" ("ID", "ELY_NRO", "ROAD_MAINTAINER_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index LRM_POSITION_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "LRM_POSITION_PK" ON "LRM_POSITION" ("ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index COMBINED
--------------------------------------------------------

CREATE UNIQUE INDEX "COMBINED" ON "PROJECT_RESERVED_ROAD_PART" ("PROJECT_ID", "ROAD_NUMBER", "ROAD_PART_NUMBER")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index LRM_POSITION_MML_IDX
--------------------------------------------------------

CREATE INDEX "LRM_POSITION_MML_IDX" ON "LRM_POSITION" ("MML_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_LINK_PRJ_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_LINK_PRJ_IDX" ON "PROJECT_LINK" ("PROJECT_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index ROAD_ADDRESS_HISTORY_CHECK
--------------------------------------------------------

CREATE UNIQUE INDEX "ROAD_ADDRESS_HISTORY_CHECK" ON "ROAD_ADDRESS" ("ROAD_NUMBER", "ROAD_PART_NUMBER", "START_ADDR_M", "END_ADDR_M", "TRACK_CODE", "DISCONTINUITY", "START_DATE", "END_DATE", "VALID_FROM", "VALID_TO", "ELY", "ROAD_TYPE", "TERMINATED")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index GAP_ROAD_ADDRESS_LINKID_ID
--------------------------------------------------------

CREATE INDEX "GAP_ROAD_ADDRESS_LINKID_ID" ON "MISSING_ROAD_ADDRESS" ("LINK_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PK_PUBLISHED_ROAD_ADDRESS
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_PUBLISHED_ROAD_ADDRESS" ON "PUBLISHED_ROAD_ADDRESS" ("NETWORK_ID", "ROAD_ADDRESS_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index GAP_ROAD_ADDRESS_ID
--------------------------------------------------------

CREATE INDEX "GAP_ROAD_ADDRESS_ID" ON "MISSING_ROAD_ADDRESS" ("ROAD_NUMBER", "ROAD_PART_NUMBER", "START_ADDR_M")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index TRAFFIC_DIR_LINK_IDX
--------------------------------------------------------

CREATE UNIQUE INDEX "TRAFFIC_DIR_LINK_IDX" ON "TRAFFIC_DIRECTION" ("LINK_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index CALIBRATION_POINT_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "CALIBRATION_POINT_PK" ON "CALIBRATION_POINT" ("ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "PROJECT_PK" ON "PROJECT" ("ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_LINK_CONNECT_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_LINK_CONNECT_IDX" ON "PROJECT_LINK" ("CONNECTED_LINK_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PLINK_ROAD_ADDRESS_IDX
--------------------------------------------------------

CREATE INDEX "PLINK_ROAD_ADDRESS_IDX" ON "PROJECT_LINK" ("ROAD_ADDRESS_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index FUNCT_CLASS_IDX
--------------------------------------------------------

CREATE UNIQUE INDEX "FUNCT_CLASS_IDX" ON "FUNCTIONAL_CLASS" ("LINK_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index ROAD_ADDRESS_LRM
--------------------------------------------------------

CREATE INDEX "ROAD_ADDRESS_LRM" ON "ROAD_ADDRESS" ("LRM_POSITION_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index CALIBRATION_POINTS_FK_UNIQUE
--------------------------------------------------------

CREATE UNIQUE INDEX "CALIBRATION_POINTS_FK_UNIQUE" ON "CALIBRATION_POINT" ("ID", "PROJECT_LINK_ID", "PROJECT_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index RESERVED_ROAD_CHECK
--------------------------------------------------------

CREATE UNIQUE INDEX "RESERVED_ROAD_CHECK" ON "PROJECT_RESERVED_ROAD_PART" ("ROAD_NUMBER", "ROAD_PART_NUMBER")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index ROAD_ADDRESS_ADDR
--------------------------------------------------------

CREATE INDEX "ROAD_ADDRESS_ADDR" ON "ROAD_ADDRESS" ("ROAD_NUMBER", "ROAD_PART_NUMBER", "TRACK_CODE")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PLINK_HISTORIC_LRM_IDX
--------------------------------------------------------

CREATE INDEX "PLINK_HISTORIC_LRM_IDX" ON "PROJECT_LINK_HISTORY" ("LRM_POSITION_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_LINK_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "PROJECT_LINK_PK" ON "PROJECT_LINK" ("ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_LINK_HIST_PRJ_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_LINK_HIST_PRJ_IDX" ON "PROJECT_LINK_HISTORY" ("PROJECT_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_LINK_ROAD_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_LINK_ROAD_IDX" ON "PROJECT_LINK" ("ROAD_NUMBER", "ROAD_PART_NUMBER")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index INCOMP_LINKID_IDX
--------------------------------------------------------

CREATE UNIQUE INDEX "INCOMP_LINKID_IDX" ON "INCOMPLETE_LINK" ("LINK_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_STATE_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_STATE_IDX" ON "PROJECT" ("STATE")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index ROAD_ADDRESS_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "ROAD_ADDRESS_PK" ON "ROAD_ADDRESS" ("ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index PROJECT_LINK_HIST_ROAD_IDX
--------------------------------------------------------

CREATE INDEX "PROJECT_LINK_HIST_ROAD_IDX" ON "PROJECT_LINK_HISTORY" ("ROAD_NUMBER", "ROAD_PART_NUMBER")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index LINK_TYPE_IDX
--------------------------------------------------------

CREATE UNIQUE INDEX "LINK_TYPE_IDX" ON "LINK_TYPE" ("LINK_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Index LRM_POSITION_LINK_ID_IDX
--------------------------------------------------------

CREATE INDEX "LRM_POSITION_LINK_ID_IDX" ON "LRM_POSITION" ("LINK_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;