-- CALIBRATION_POINTS values:
-- 0 No calibration points
-- 1 Calibration point at the end of the link
-- 2 Calibration point at the beginning of the link
-- 3 Calibration point at the beginning and at the end of the link
--
-- CALIBRATION_POINTS_SOURCE values:
-- 0 No calibration point
-- 1 Road address source
-- 2 Project link source
--
-- CalibrationPointType values:
-- 0 No calibration point
-- 1 User added calibration point
-- 2 Junction calibration point
-- 3 Road address calibration point
--
-- START_CALIBRATION_POINT, END_CALIBRATION_POINT, ORIG_START_CALIBRATION_POINT and ORIG_END_CALIBRATION_POINT
-- contain CalibrationPointType values

ALTER TABLE PROJECT_LINK ADD (START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK ADD (END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK ADD (ORIG_START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK ADD (ORIG_END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);

UPDATE PROJECT_LINK SET START_CALIBRATION_POINT =
    CASE
      WHEN CALIBRATION_POINTS_SOURCE = 1 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 2 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 3 THEN 2
      WHEN CALIBRATION_POINTS_SOURCE = 4 THEN 4
      ELSE 99
    END
  WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK SET END_CALIBRATION_POINT =
    CASE
      WHEN CALIBRATION_POINTS_SOURCE = 1 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 2 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 3 THEN 2
      WHEN CALIBRATION_POINTS_SOURCE = 4 THEN 4
      ELSE 99
    END
  WHERE CALIBRATION_POINTS IN (1, 3);
UPDATE PROJECT_LINK SET ORIG_START_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK SET ORIG_END_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (1, 3);

ALTER TABLE PROJECT_LINK DROP COLUMN CALIBRATION_POINTS;
ALTER TABLE PROJECT_LINK DROP COLUMN CALIBRATION_POINTS_SOURCE;

ALTER TABLE PROJECT_LINK_HISTORY ADD (START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK_HISTORY ADD (END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK_HISTORY ADD (ORIG_START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK_HISTORY ADD (ORIG_END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);

UPDATE PROJECT_LINK_HISTORY SET START_CALIBRATION_POINT =
    CASE
      WHEN CALIBRATION_POINTS_SOURCE = 1 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 2 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 3 THEN 2
      WHEN CALIBRATION_POINTS_SOURCE = 4 THEN 4
      ELSE 99
    END
  WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK_HISTORY SET END_CALIBRATION_POINT =
    CASE
      WHEN CALIBRATION_POINTS_SOURCE = 1 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 2 THEN 3
      WHEN CALIBRATION_POINTS_SOURCE = 3 THEN 2
      WHEN CALIBRATION_POINTS_SOURCE = 4 THEN 4
      ELSE 99
    END
  WHERE CALIBRATION_POINTS IN (1, 3);
UPDATE PROJECT_LINK_HISTORY SET ORIG_START_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK_HISTORY SET ORIG_END_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (1, 3);

ALTER TABLE PROJECT_LINK_HISTORY DROP COLUMN CALIBRATION_POINTS;
ALTER TABLE PROJECT_LINK_HISTORY DROP COLUMN CALIBRATION_POINTS_SOURCE;

ALTER TABLE CALIBRATION_POINT DROP CONSTRAINT CP_TYPE_CHK;

UPDATE CALIBRATION_POINT SET "TYPE" = 3 WHERE "TYPE" = 2;
UPDATE CALIBRATION_POINT SET "TYPE" = 2 WHERE "TYPE" = 1;
UPDATE CALIBRATION_POINT SET "TYPE" = 1 WHERE "TYPE" = 0;

-- Allowed types:
-- 1 User added calibration point
-- 2 Junction calibration point
-- 3 Road address calibration point
ALTER TABLE CALIBRATION_POINT ADD CONSTRAINT CP_TYPE_CHK CHECK ("TYPE" in (1, 2, 3));
