CREATE UNIQUE INDEX PROJECT_CALIBRATION_POINT_I ON PROJECT_CALIBRATION_POINT (ID, PROJECT_LINK_ID, PROJECT_ID);

CREATE INDEX UNADDRESSED_ROAD_LINK_I ON UNADDRESSED_ROAD_LINK (ROAD_NUMBER, ROAD_PART_NUMBER, START_ADDR_M);

CREATE INDEX UNADDRESSED_ROAD_LINK_LINKID_I ON UNADDRESSED_ROAD_LINK (LINK_ID);

-- TODO Postgres style
-- CREATE INDEX UNADDRESSED_ROAD_LINK_GEOM_I ON UNADDRESSED_ROAD_LINK (GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX PROJECT_LINK_ROADWAY_I ON PROJECT_LINK (ROADWAY_ID);

CREATE INDEX PROJECT_LINK_CONNECT_I ON PROJECT_LINK (CONNECTED_LINK_ID);

CREATE INDEX PROJECT_LINK_HIST_PRJ_I ON PROJECT_LINK_HISTORY (PROJECT_ID);

CREATE INDEX PROJECT_LINK_HIST_ROAD_I ON PROJECT_LINK_HISTORY (ROAD_NUMBER, ROAD_PART_NUMBER);

CREATE INDEX PROJECT_LINK_PRJ_I ON PROJECT_LINK (PROJECT_ID);

CREATE INDEX PROJECT_LINK_ROAD_I ON PROJECT_LINK (ROAD_NUMBER, ROAD_PART_NUMBER);

CREATE INDEX PROJECT_STATE_I ON PROJECT (STATE);

CREATE INDEX ROADWAY_ADDR_I ON ROADWAY (ROAD_NUMBER, ROAD_PART_NUMBER, TRACK);

CREATE INDEX ROADWAY_CURRENT_I ON ROADWAY (VALID_TO, END_DATE, TERMINATED);

-- TODO Postgres style
-- CREATE INDEX LINEAR_LOCATION_GEOMETRY_I ON LINEAR_LOCATION (GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX LINEAR_LOCATION_LINK_ID_I ON LINEAR_LOCATION (LINK_ID);

CREATE INDEX ROAD_NAME_CURRENT_I ON ROAD_NAME (VALID_TO, END_DATE, ROAD_NUMBER);

CREATE INDEX CALIBRATION_POINT_I ON CALIBRATION_POINT(ROADWAY_POINT_ID);

CREATE INDEX CALIBRATION_POINT_II ON CALIBRATION_POINT(ROADWAY_POINT_ID, LINK_ID, START_END);

CREATE INDEX CALIBRATION_POINT_III ON CALIBRATION_POINT(LINK_ID, START_END);

CREATE INDEX LOCATION_I ON LINEAR_LOCATION(ID, ROADWAY_NUMBER, LINK_ID, START_MEASURE, END_MEASURE, SIDE, VALID_FROM, VALID_TO);

CREATE INDEX LINK_I ON LINK(ID, SOURCE, ADJUSTED_TIMESTAMP);

CREATE INDEX ROADWAY_POINT_I ON ROADWAY_POINT (ID, ROADWAY_NUMBER, ADDR_M);

-- TODO Postgres style
--CREATE INDEX NODE_GEOMETRY_I ON NODE (COORDINATES) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX NODE_NUMBER_I ON NODE (NODE_NUMBER);

CREATE INDEX ROADWAY_NUMBER1 ON ROADWAY (ROADWAY_NUMBER);
