ALTER TABLE PROJECT_LINK ADD (START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK ADD (END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK ADD (ORIG_START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK ADD (ORIG_END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);

UPDATE PROJECT_LINK SET START_CALIBRATION_POINT = CALIBRATION_POINTS_SOURCE WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK SET END_CALIBRATION_POINT = CALIBRATION_POINTS_SOURCE WHERE CALIBRATION_POINTS IN (1, 3);
UPDATE PROJECT_LINK SET ORIG_START_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK SET ORIG_END_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (1, 3);

ALTER TABLE PROJECT_LINK DROP COLUMN CALIBRATION_POINTS;
ALTER TABLE PROJECT_LINK DROP COLUMN CALIBRATION_POINTS_SOURCE;

ALTER TABLE PROJECT_LINK_HISTORY ADD (START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK_HISTORY ADD (END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK_HISTORY ADD (ORIG_START_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);
ALTER TABLE PROJECT_LINK_HISTORY ADD (ORIG_END_CALIBRATION_POINT NUMBER(2,0) DEFAULT 0 NOT NULL);

UPDATE PROJECT_LINK_HISTORY SET START_CALIBRATION_POINT = CALIBRATION_POINTS_SOURCE WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK_HISTORY SET END_CALIBRATION_POINT = CALIBRATION_POINTS_SOURCE WHERE CALIBRATION_POINTS IN (1, 3);
UPDATE PROJECT_LINK_HISTORY SET ORIG_START_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (2, 3);
UPDATE PROJECT_LINK_HISTORY SET ORIG_END_CALIBRATION_POINT = 3 WHERE CALIBRATION_POINTS IN (1, 3);

ALTER TABLE PROJECT_LINK_HISTORY DROP COLUMN CALIBRATION_POINTS;
ALTER TABLE PROJECT_LINK_HISTORY DROP COLUMN CALIBRATION_POINTS_SOURCE;

UPDATE CALIBRATION_POINT SET "TYPE" = 3 WHERE "TYPE" = 2;
UPDATE CALIBRATION_POINT SET "TYPE" = 2 WHERE "TYPE" = 1;
UPDATE CALIBRATION_POINT SET "TYPE" = 1 WHERE "TYPE" = 0;
