DROP TRIGGER IF EXISTS ROADNAME_SEQ_TRIGGER ON ROAD_NAME;

CREATE OR REPLACE FUNCTION ROADNAME_NEW_ID()
  RETURNS trigger AS
$$
BEGIN
NEW.ID := ROAD_NAME_SEQ.NEXTVAL;
RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ROADNAME_SEQ_TRIGGER
BEFORE INSERT ON ROAD_NAME
FOR EACH ROW
WHEN (NEW.ID IS NULL)
EXECUTE PROCEDURE ROADNAME_NEW_ID();


DROP TRIGGER IF EXISTS VALIDTODATE_VALIDATION ON ROADWAY;

CREATE OR REPLACE FUNCTION VALIDTO_VALIDFROM()
  RETURNS trigger AS
$$
BEGIN
NEW.VALID_TO := NEW.VALID_FROM;
RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER VALIDTODATE_VALIDATION
BEFORE INSERT OR UPDATE ON ROADWAY
FOR EACH ROW
WHEN (NEW.START_DATE = NEW.END_DATE)
EXECUTE PROCEDURE VALIDTO_VALIDFROM();
