ALTER TABLE "PROJECT_LINK" RENAME COLUMN GEOMETRY TO GEOMETRY_STRING;
ALTER TABLE "PROJECT_LINK" ADD (GEOMETRY SDO_GEOMETRY);
ALTER TABLE "PROJECT_LINK" ADD (ORIGINAL_START_ADDR_M NUMBER(8,0) NOT NULL);
ALTER TABLE "PROJECT_LINK" ADD (ORIGINAL_END_ADDR_M NUMBER(8,0) NOT NULL);

ALTER TABLE "PROJECT_LINK_HISTORY" RENAME COLUMN GEOMETRY TO GEOMETRY_STRING;
ALTER TABLE "PROJECT_LINK_HISTORY" ADD (GEOMETRY SDO_GEOMETRY);
ALTER TABLE "PROJECT_LINK_HISTORY" ADD (ORIGINAL_START_ADDR_M NUMBER(8,0) NOT NULL);
ALTER TABLE "PROJECT_LINK_HISTORY" ADD (ORIGINAL_END_ADDR_M NUMBER(8,0) NOT NULL);