CREATE TABLE PROJECT_LINK_NAMES
(
	"ID" NUMBER,
	"PROJECT_ID" NUMBER,
	"ROAD_NUMBER" NUMBER,
	"ROAD_NAME" VARCHAR2(255 BYTE)
);

CREATE SEQUENCE "PROJECT_LINK_NAME_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
ALTER TABLE "PROJECT_LINK_NAMES" ADD CONSTRAINT "PROJECT_LINK_NAMES_PK" PRIMARY KEY ("ID");
ALTER TABLE "PROJECT_LINK_NAMES" ADD CONSTRAINT "PROJECT_LINK_NAMES_FK" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("ID") ENABLE;