ALTER TABLE PROJECT_LINK ADD COLUMN ORIGINAL_START_ADDR_M INTEGER NOT NULL;
ALTER TABLE PROJECT_LINK ADD COLUMN ORIGINAL_END_ADDR_M INTEGER NOT NULL;
ALTER TABLE PROJECT_LINK_HISTORY ADD COLUMN ORIGINAL_START_ADDR_M INTEGER NOT NULL;
ALTER TABLE PROJECT_LINK_HISTORY ADD COLUMN ORIGINAL_END_ADDR_M INTEGER NOT NULL;
