ALTER TABLE "PROJECT_LINK" ADD (ORIGINAL_START_ADDR_M NUMBER(8,0) NOT NULL);
ALTER TABLE "PROJECT_LINK" ADD (ORIGINAL_END_ADDR_M NUMBER(8,0) NOT NULL);
ALTER TABLE "PROJECT_LINK_HISTORY" ADD (ORIGINAL_START_ADDR_M NUMBER(8,0) NOT NULL);
ALTER TABLE "PROJECT_LINK_HISTORY" ADD (ORIGINAL_END_ADDR_M NUMBER(8,0) NOT NULL);