ALTER TABLE "ROADWAY_CHANGES" ADD (ORDER_IN_TABLE NUMBER(8,0) NOT NULL);

CREATE SEQUENCE ROADWAY_CHANGE_LINK MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;

CREATE TABLE ROADWAY_CHANGES_LINK(
  PROJECT_ID NUMBER(38,0) NOT NULL,
  ORDER_NUMBER NUMBER(8, 0) NOT NULL,
  PROJECT_LINK_ID NUMBER(38,0) NOT NULL,
  CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
  CONSTRAINT PROJECT_LINK_FK FOREIGN KEY (PROJECT_LINK_ID) REFERENCES PROJECT_LINK (ID)
);