FROM node:alpine
RUN apk --update add openjdk7-jre
ARG JENKINS_UID=1000
RUN adduser -D -S -u $JENKINS_UID jenkins
RUN mkdir /home/jenkins/package && \
    mkdir /home/jenkins/package/viite-UI
RUN npm install grunt -g
RUN chown -R jenkins /home/jenkins