import java.net.URI
def get_environment() {
    //if (env.BRANCH_NAME.startsWith("master")) { return "Staging" }
    return "staging"
}

def get_pollSCM_trigger() {
    if (env.BRANCH_NAME.equals("master")) { return "* * * * *" }
    return ""
}

pipeline {
    agent any
    environment {
        NOTIFY_SLACK_SUBJECT = "${JOB_NAME} - <${RUN_DISPLAY_URL}|${BUILD_DISPLAY_NAME}>"
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: "25"))
        disableConcurrentBuilds()
    }
    triggers {
        pollSCM(get_pollSCM_trigger())
    }
    stages {
        stage("Setup") {
            when {
                expression {
                    get_environment()?.trim()
                }
            }
            steps {
                    script {

                        STAGE_FRONTEND_BUILD_CMD = [
                            "mkdir tmp",
                            "npm install",
                            "export TMPDIR=/home/jenkins/tmp",
                            "yarn install",
                            "grunt deploy --target=${get_environment()?.trim()}",
                            "cp -r /data1/jenkins/workspace/viite/Deploy-Staging/dist /home/jenkins/package/viite-UI/",
                            "cp -r /data1/jenkins/workspace/viite/Deploy-Staging/node_modules /home/jenkins/package/viite-UI/",
                            "cd /home/jenkins/package/viite-UI"
                        ].join(" && ")

                        STAGE_FRONTEND_TEST_CMD = [
                            "grunt test"
                        ].join(" && ")
                        def sbt_proxy = new URI(http_proxy)

                        def java_opts = [
                            "-Dhttp.proxyHost=${sbt_proxy.getHost()}",
                            "-Dhttp.proxyPort=${sbt_proxy.getPort()}",
                            "-Dhttp.nonProxyHosts=*.vally.local",
                            "-DproxySet=true"
                        ].join(" ")

                        STAGE_BACKEND_BUILD_CMD = [
                            "~/sbt/bin/./sbt $java_opts -Ddigiroad2.env=${get_environment()?.trim()} assembly",
                            "cp -r /data1/jenkins/workspace/viite/Deploy-Staging/target/scala-2.11/viite-assembly-0.1.0-SNAPSHOT.jar /home/jenkins/package/"
                        ].join(" && ")

                        STAGE_PACKAGE_CMD = [
                            "cd /home/jenkins/package/",
                            "jar -cvf viite-assembly-0.1.0.war *"
                        ].join(" && ")

                        STAGE_PUBLISH_CMD = [
                            "mvn deploy:deploy-file",
                            "-DgroupId=fi.liikennevirasto.viite",
                            "-DartifactId=viite-staging",
                            "-Dversion=1.0.0",
                            "-DgeneratePom=true",
                            "-Dpackaging=war",
                            "-DrepositoryId=nexus3",
                            "-Durl=http://livibuild04.vally.local/nexus/repository/viite/",
                            "-Dfile=/home/jenkins/package/viite-assembly-0.1.0.war",
                            "-q",
                            "--batch-mode"
                        ].join(" ")

                        START_SSH_AGENT = [
                            "touch start_agent.sh",
                            'echo "$(ssh-agent)" > start_agent.sh',
                            "echo AQUI!",
                            "cat start_agent.sh",
                            "chmod 711 start_agent.sh",
                            "source start_agent.sh"
                        ].join(" && ")

                        STAGE_DEPLOY_CMD = [
                            "cd /home/jenkins/",
                            //"bundle install",
                            "bundle exec cap staging deploy"
                        ].join(" && ")
                    }
            }
        }
        stage("Prepare") {
            when {
                expression {
                    get_environment()?.trim()
                }
            }
            steps {
                sh "cp /data1/ci/maven/* ci/config/"
                script {

                    echo "Running publish... (skipped for now) "

                    def jenkins_uid = sh(returnStdout: true, script: "id -u").trim()
                    def build_args = [
                        "--build-arg http_proxy=${http_proxy}",
                        "--build-arg https_proxy=${http_proxy}",
                        "--build-arg no_proxy=${no_proxy}",
                        "--build-arg JENKINS_UID=${jenkins_uid}"
                    ].join(" ")
                    docker.build(
                        "viite-frontend-node",
                        "${build_args} -f ci/Dockerfile.node ci"
                    )
                    docker.build(
                        "viite-backend-sbt",
                        "${build_args} -f ci/Dockerfile.backend ci"
                    )
                    docker.build(
                        "viite-maven-publish",
                        "${build_args} -f ci/Dockerfile.maven ci"
                    )
                    docker.build(
                        "viite-capistrano",
                        "${build_args} -f ci/Dockerfile.ruby ci"
                     )
                }
            }
            //post {
            //    failure {
                    //slackSend(
                    //    color: "danger",
                    //    message: "${NOTIFY_SLACK_SUBJECT}\nStage ${STAGE_NAME} failure! Check <${BUILD_URL}console|console>!"
                    //)
            //    }
            //}
        }
        stage("Build: Frontend") {
            agent {
                docker {
                    image "viite-frontend-node"
                    reuseNode true
                    args "-v viite-package-${get_environment()?.trim()}:/home/jenkins/package"
                }
            }
            when {
                beforeAgent true
                expression {
                    get_environment()?.trim()
                }
            }
            steps {
                //sh STAGE_FRONTEND_BUILD_CMD
                echo "Running frontend build... (skipped for now)"
            }
            //post {
            //    failure {
                    //slackSend(
                    //    color: "danger",
                    //    message: "${NOTIFY_SLACK_SUBJECT}\nStage ${STAGE_NAME} failure! Check <${BUILD_URL}console|console>!"
                    //)
            //    }
            //}
        }
		stage("Build: Backend") {
            agent {
                docker {
                    image "viite-backend-sbt"
                    reuseNode true
                    args "-v viite-package-${get_environment()?.trim()}:/home/jenkins/package"
                }
            }
            when {
                beforeAgent true
                expression {
                    get_environment()?.trim()
                }
            }
            steps {
                //sh STAGE_BACKEND_BUILD_CMD
                echo "Skipped for now"
            }
            //post {
            //    failure {
                    //slackSend(
                    //    color: "danger",
                    //    message: "${NOTIFY_SLACK_SUBJECT}\nStage ${STAGE_NAME} failure! Check <${BUILD_URL}console|console>!"
                    //)
            //    }
            //}
        }
        stage("Package & Publish") {
            agent {
                docker {
                    image "viite-maven-publish"
                    reuseNode true
                    args "-v viite-package-${get_environment()?.trim()}:/home/jenkins/package"
                }
            }
            when {
                beforeAgent true
                expression {
                    get_environment()?.trim()
                }
            }
            steps {
                //sh STAGE_PACKAGE_CMD
                //sh STAGE_PUBLISH_CMD
				echo "Running publish... (skipped for now)"
            }
            //post {
            //    failure {
                    //slackSend(
                    //    color: "danger",
                    //    message: "${NOTIFY_SLACK_SUBJECT} - Stage ${STAGE_NAME} failure!\nCheck <${BUILD_URL}console|console>!"
                    //)
            //    }
            //}
        }
       stage("Deploy") {

            agent {
                docker {
                    image "viite-capistrano_2"
                    reuseNode true
                }
            }
            when {
                beforeAgent true
                expression {
                    get_environment()?.trim()
                }
            }
            steps {

                //sh START_SSH_AGENT
                withCredentials([file(credentialsId: 'ssh_config', variable: 'SSH_CONFIG'),
                                 file(credentialsId: 'SSH_KNOWN_HOSTS', variable: 'KNOWN_HOSTS'),
                                 file(credentialsId: 'ID_RSA', variable: 'ID_RSA'),
                                 file(credentialsId: 'ID_RSA_PUB', variable: 'ID_RSA_PUB')]) {
                    sh "mkdir /home/jenkins/.ssh/ && cp ${SSH_CONFIG} /home/jenkins/.ssh/ && cp ${KNOWN_HOSTS} /home/jenkins/.ssh/"
                    sh "cp ${ID_RSA_PUB} /home/jenkins/.ssh/"
                    sh "cp ${ID_RSA} /home/jenkins/.ssh/"
                }
                // sshagent ( ['RSA_KEY']) {
                //    sh STAGE_DEPLOY_CMD
                // }

                //sh "ls -l"
                //sh "ssh-agent /bin/sh && ssh-add /home/jenkins/.ssh/id_rsa"
                sh STAGE_DEPLOY_CMD
            }
            //post {
            //    failure {
                    //slackSend(
                    //    color: "danger",
                    //    message: "${NOTIFY_SLACK_SUBJECT} - Stage ${STAGE_NAME} failure!\nCheck <${BUILD_URL}console|console>!"
                    //)
            //    }
            //}
        }
    }
    post {
        always {
            //slackSend(
            //    color: currentBuild.currentResult.equals("SUCCESS") ? "good" : "danger",
            //    message: "${NOTIFY_SLACK_SUBJECT}\nJob ${currentBuild.currentResult}! More info <${BUILD_URL}|here>."
            //)
            deleteDir()
        }
    }
}