AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation managed taskdefinition
Parameters:
  RepositoryURL:
    Type: String
    Description: URL to repository, where the container is, e.g. 012345678910.dkr.ecr.eu-west-1.amazonaws.com
  ECSTaskRoleName:
    Type: String
    Default: qa-viite-ecs-task-role
    Description: Name of ECS task definition task role
  ApiS3BucketName:
    Type: String
    Default: qa-vayla-viite-api-store-bucket
    Description: Name of s3 bucket for apis
  ApiS3ObjectTTLSeconds:
    Type: Number
    Default: 300
    Description: Seconds, how long s3 object can be fetched after last modification
  DynamicLinkNetworkS3BucketName:
    Type: String
    Default: qa-vayla-viite-dynamic-link-network-bucket
    Description: Name of s3 bucket for dynamic link network change sets
Resources:
  # This is a role which is used by the ECS tasks themselves.
  ECSTaskExecutionRoleForViite:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:DescribeParameters'
                  # Allow the ECS Tasks to download images from ECR
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'

                  # Allow the ECS tasks to upload logs to CloudWatch
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRoleForViite.Arn
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ECSTaskRoleName}'
      ContainerDefinitions:
        -
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/QA-viite-test-ECS-logs
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs
          PortMappings:
            - ContainerPort: 9080
              HostPort: 9080
              Protocol: tcp
          Cpu: 0
          Environment:
            - Name: userProvider
              Value: fi.vaylavirasto.viite.dao.PostGISUserProvider
            - Name: eventBus
              Value: fi.liikennevirasto.digiroad2.DigiroadEventBus
            - Name: oagProxyServer
              Value: oag.vayla.fi
            - Name: oagProxyURL
              Value: 'https://oag.vayla.fi'
            - Name: rasterServiceURL
              Value: 'https://api.vaylapilvi.fi/rasteripalvelu-mml'
            - Name: kgvRoadlink.frozen
              Value: 'true'
            - Name: vkmUrl
              Value: 'https://api.vaylapilvi.fi'
            - Name: http.proxySet
              Value: 'false'
            - Name: http.proxyHost
              Value: 127.0.0.1
            - Name: http.nonProxyHosts
              Value: 127.0.0.1
            - Name: importOnlyCurrent
              Value: 'false'
            - Name: authenticationTestMode
              Value: 'false'
            - Name: bonecp.jdbcUrl
              Value: 'jdbc:postgresql://rdspg13test.chw6qe2cqnfv.eu-west-1.rds.amazonaws.com:5432/viitetest'
            - Name: bonecp.username
              Value: viitetest
            - Name: conversion.bonecp.jdbcUrl
              Value: 'jdbc:postgresql://vd1bbyq5el8tjd2.c8dj2qlvf50d.eu-west-1.rds.amazonaws.com:5432/drkonv'
            - Name: conversion.bonecp.username
              Value: drkonv
            - Name: authentication.admin.basic.username
              Value: admin
            - Name: env
              Value: QA
            - Name: apiS3BucketName
              Value: !Sub '${ApiS3BucketName}'
            - Name: apiS3ObjectTTLSeconds
              Value: !Sub '${ApiS3ObjectTTLSeconds}'
            - Name: dynamicLinkNetworkS3BucketName
              Value: !Sub '${DynamicLinkNetworkS3BucketName}'
            - Name: kgvEndpoint
              Value: 'https://api.vaylapilvi.fi/paikkatiedot/ogc/features/collections'
          Secrets:
            - Name: bonecp.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Viite/QA/rds.viite.db.password'
            - Name: conversion.bonecp.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Viite/QA/conversion.db.password'
            - Name: authentication.admin.basic.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Viite/QA/authentication.admin.basic.password'
            - Name: vkmApiKey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Viite/QA/vkmApiKey'
            - Name: rasterServiceApiKey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Viite/QA/rasterServiceApiKey'
            - Name: kgvApiKey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Viite/QA/kgvApiKey'
          MemoryReservation: 2048
          Image: !Sub '${RepositoryURL}/viite-qa:latest'
          Name: viite-test
          HealthCheck:
            StartPeriod: 15
            Command:
              - CMD-SHELL
              - curl -f http://127.0.0.1:9080/api/ping/ || exit 1
      Memory: '4096'
      Family: QA-viite-test
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '2048'
      Tags:
        - Key: Name
          Value: Viite-QA
        - Key: Environment
          Value: QA
        - Key: Owner
          Value: Vayla
        - Key: Project
          Value: Viite
        - Key: Application
          Value: Viite

